Adds simple calculator form
CodeSoom/week1-assignment-2 pull request #168
Opened 2022-08-02 11:54 UTC by 0-Chan

트레이너님 안녕하세요? 2번 째 간단계산기 과제 PR 드립니다.^^

아직 완성 되지 않아서, 테스트 코드 2개 정도는 통과하지 못한 상태입니다. (lint 도 아직 체크 하지 못했습니다...)

전체적인 구조를 보시고 뭔가 이상한 부분이 있다면 말씀 해주세요!! 감사합니닷.

2022-08-02 12:38 UTC, daadaadaah requested changes
1. `if ~ else`
- `if ~ else` 같은 경우, 대표적으로 코드 가독성이 좋지 않은 표현이예요!  `if ~ else` 문을 사용하지 않고 코드를 표현할 수 있는 방법이 있을까요?
- 가동성이 좋지 않은 코드에 대해 더 공부해보고 싶으시면, [클린코드](http://www.yes24.com/Product/Goods/11681152) 같은 도서 한번 읽어보시면 도움이 되실 거예요!

2. 표기법 
- JS에서는 주로 어떤 표기법을 사용하는지에 대해 한번 공부해보세요!

2022-08-02 12:38 UTC, daadaadaah commented on src/index.js
> +let operatorClicked = false;
코드숨 과제를 진행할 때는 가능하면 `let` 을 사용하지 않고 진행해주세요!

2022-08-02 15:38 UTC, 0-Chan commented on src/index.js
> +let operatorClicked = false;
제가 지난 과제 처럼 object를 구조 분해 할당하지 않고 let을 쓰는 습관이 나와버렸네요... 

아마 let을 쓰지 않을 때 어떤 장점이 있는지 제대로 이해하지 못한 것에서 비롯된 것 같은데요.

찾아보니 RORO 패턴이라는게 보이던데, 이 패턴이 let을 쓰지 않는 가장 큰 이유일까요?

2022-08-03 08:15 UTC, 0-Chan commented
> 1. `if ~ else`
> 
> * `if ~ else` 같은 경우, 대표적으로 코드 가독성이 좋지 않은 표현이예요!  `if ~ else` 문을 사용하지 않고 코드를 표현할 수 있는 방법이 있을까요?
> * 가동성이 좋지 않은 코드에 대해 더 공부해보고 싶으시면, [클린코드](http://www.yes24.com/Product/Goods/11681152) 같은 도서 한번 읽어보시면 도움이 되실 거예요!
> 
> 2. 표기법
> 
> * JS에서는 주로 어떤 표기법을 사용하는지에 대해 한번 공부해보세요!

- 수정할 목록 // 요구 사항
- [x] `if ~ else` 사용하지 않기
- [x] 표기법 (camelCase로 표기법 변경!)
- [x] let 사용하지 않기
<br>

- [x] 인수 테스트 통과
- [ ] ESLint 체크

 빠른 코드리뷰 정말 감사드려요!
짚어주신 내용에 토대로 commit을 남겨 보았습니다.

1. if ~ else
 Early return 방법을 적용 했습니다. 각 `if`문에 `return`을 넣었더니 `else`가 필요 없어졌고, 이를 제거하는 방식으로 가독성 높였습니다.

2. 표기법
 기존에는 변수를 snake_case로 작성 했는데요. AirBnB에서 제공하는 JS 코딩 컨벤션을 참고하여 모두 camelCase로 바꾸었습니다.

3. let 제거
 let으로 선언된 `operatorClicked` 변수를 object에 포함하여 let을 제거 했습니다.

---
##### 질문 사항:
 아직 **lint 체크**를 통과하지 못하였는데요. 기본적인 indentation 등은 통과 했지만, `no-param-reassign` 이라는 항목만 걸려있습니다.

[왜 하지 말라는지](https://github.com/airbnb/javascript#functions--reassign-params)는 알겠지만 이걸 해결하려면 let을 쓰는 방법 밖에 떠오르지 않네요...  
혹시 로직을 바꿔야할까요?!

2022-08-03 14:40 UTC, daadaadaah requested changes
> 아직 lint 체크를 통과하지 못하였는데요. 기본적인 indentation 등은 통과 했지만, no-param-reassign 이라는 항목만 걸려있습니다.
[왜 하지 말라는지](https://github.com/airbnb/javascript#functions--reassign-params)는 알겠지만 이걸 해결하려면 let을 쓰는 방법 밖에 떠오르지 않네요...
혹시 로직을 바꿔야할까요?!

- 전체적으로 로직이 복잡해서😂 한번 바꿔보는 것도 좋을 거 같아요! calculate 함수의 return을 배열이 아닌 다른 형태로 관리해보거나 `operatorClicked` 같은 변수 없이도 구현하는 방법이 없을까? 라는 등 여러 방법을 시도해보시는 걸 추천드립니다!😊

2022-08-03 14:40 UTC, daadaadaah commented on src/index.js
> +  }
1. if문이 너무 많은데, 좀더 간단히 객체를 활용해보시는건 어떠신가요? 
2. return 값을 보면 똑같은 값을 넣어주는데, 2개의 요소를 지닌 배열로 return 해주시는 이유가 궁금합니다! 똑같은 값이면, 1개의 값으로 return해주면 되지 않을까 라는 생각이 들거든용!ㅎㅎ

2022-08-03 14:40 UTC, daadaadaah commented on src/index.js
> +  function handleClickNumber(value) {
`value`보다 좀더 의도가 드러나는 단어로 표현해봅시다!ㅎㅎ

2022-08-03 14:40 UTC, daadaadaah commented on src/index.js
> +        count: 0, prevNum: 0, lastOperator: '', operatorClicked: false,
1. prevNum 처럼 축약어보다 full name을 사용해봅시다!ㅎㅎ
2.`lastOperator`에서 last 말고 다른 단어로 표현해보시는건 어떠신가요? 이 단어를 보고 firstOperator 등 다른 연산자가 있나? 라는 생각이 들었거든용!ㅎㅎ

2022-08-03 14:41 UTC, daadaadaah commented on src/index.js
> +let operatorClicked = false;
음..RORO 패턴이 무엇이고, 어떤 장점이 있는 패턴으로 공부하신건가용?ㅎㅎ

2022-08-04 11:46 UTC, 0-Chan commented on src/index.js
> +  function handleClickNumber(value) {
value를 의도가 드러나는 `digit` 이라는 이름으로 바꾸었습니다.

2022-08-04 11:47 UTC, 0-Chan commented on src/index.js
> +        count: 0, prevNum: 0, lastOperator: '', operatorClicked: false,
1. 축약어를 사용하지 않고 `previousNumber` 이라는 이름으로 대체 하였습니다.
2. 모호할 수 있는 변수 명을 `previousSymbol` 으로 바꾸어 보았습니다.

2022-08-04 11:57 UTC, 0-Chan commented on src/index.js
> +  }
- 수정할 목록 // 요구 사항
- [x] ~~`if ~ else` 사용하지 않기~~
- [x] ~~표기법 (camelCase로 표기법 변경!)~~
- [x] ~~let 사용하지 않기~~
- [x] calculate 함수 내에 if문 제거 (object literal로)
- [x] 모호하거나 축약된 이름 변경
- [x] operatorClicked 변수 삭제
- [ ] 전체적인 로직 변경...   
<br>

- [x] 인수 테스트 통과
- [ ] ESLint 체크

세세한 리뷰 감사드립니다!
1. 확실히 calculate 함수에 if문이 너무 많아 가독성이 나빴던 것 같습니다... Object literal 방법으로 수정 해보았습니다.ㅎㅎ
2. 생각해보니 그렇네요...!! 굳이 배열을 안쓰고 밖에서 const 를 선언한 변수에 넣었습니다!
---
##### 질문 사항:
 아직도 **lint 체크**를 통과하지 못하였는데요. 뭔가 벽에 막힌듯 잘 떠오르지가 않습니다 ㅜㅜ. 지금 가장 문제가 연산자에 대한 handelClick이 맨 처음 이루어졌을 때 이걸 어떻게 해결하느냐 인데요. 어.. render()을 한번 더 돌리는 방식은 아닌 것 같아서 고민을 좀 더 해보겠습니다!! (76, 77, 78 라인)

2022-08-04 14:24 UTC, daadaadaah requested changes
1. 지금 1 -> + -> 2 -> = -> 3 -> + 이런 순서로 입력하면, 계산기가 정상적으로 동작하지 않습니다!
이 부분도 한번 체크해주세요!ㅎㅎ
2. `count`와 `previousNumber`의 차이는 무엇인가요? `previousNumber`는 어떤 값을 다루는 변수인가요?

2022-08-04 14:24 UTC, daadaadaah commented on src/index.js
> +  count = 0, previousNumber = 0, previousSymbol = '',
`symbol` 이란 단어는 자바스크립트에서의 symbol이랑 혼동을 줄 것 같아요! 다른 단어로 표현해봅시당!ㅎㅎ

2022-08-04 14:24 UTC, daadaadaah commented on src/index.js
> +  function calculate(number1, number2, symbol) {
매개변수가 점점 많아지면 어떤 불편함이 있을까요?
[RORO 패턴](https://usecode.pw/elegant-patterns-in-modern-java-script-roro/) 에 대해 한번 공부해봅시당!

2022-08-04 14:24 UTC, daadaadaah commented on src/index.js
> +    return symbols[symbol]?.(number1, number2) ?? 'Math symbol is not vaild.';
예외 상황까지 고려하신 점 잘하셨습니다. 👍
다만, return 값의 타입이 다르면, 문제가 발생할 것 같아요!
일단, 간단한 계산기를 만드는 게 과제이니, 예외 상황은 생략하고 과제를 진행해봅시다!ㅎㅎ

2022-08-06 10:52 UTC, 0-Chan commented on src/index.js
> +  count = 0, previousNumber = 0, previousSymbol = '',
JS에 `symbol`이 있다는 걸 몰랐네요! 말씀하신 대로 혼동을 줄 수 있을 것 같아서 다시 operator로 돌아갔습니다.

2022-08-06 11:04 UTC, 0-Chan commented on src/index.js
> +    return symbols[symbol]?.(number1, number2) ?? 'Math symbol is not vaild.';
넵 ㅋㅋㅋ.. 혼자 생각에 몇몇 예외 처리를 넣어보았는데. 아무래도 사족이었던 것 같네요.😅 
Type 문제가 일어날 수 있으니 제거 하였습니다.

2022-08-06 11:48 UTC, 0-Chan commented
> 1. 지금 1 -> + -> 2 -> = -> 3 -> + 이런 순서로 입력하면, 계산기가 정상적으로 동작하지 않습니다!
>    이 부분도 한번 체크해주세요!ㅎㅎ
> 2. `previousNumber`는 어떤 값을 다루는 변수인가요?

- 수정할 목록 // 과제 요구 사항
- [x] `symbol`을 다시 `operator`로 변경
- [x] Nullish coalescing operaotr(`??`) 예외 처리 제거
- [x] `=` 이후에 연속 계산이 안되는 버그 수정
- [ ] 11 + 111 처럼 같은 상황에서 입력이 안되는 버그
<br>

- [x] 인수 테스트 통과
- [ ] ESLint 체크 (no-param-reassign)

1. `=` 이후에 연속 계산 버그<br> : `=`이 눌렸을 때 render()에 previousNumber를 0을 넣음으로써 버그를 수정했습니다. 
2. `previousNumber` 역할<br> : 이 변수는 `연산자` 이후에 `숫자`가 눌렸을 때 연산을 위해 임시로 저장해두는 변수입니다!
근데 지금 이거 작성하다가 버그(11 + 111 입력이 안되는)를 발견했네요... 이거 내일 까지 수정 해보겠습니다ㅜㅜ

---
##### 질문 사항:
 혹시 `previousNumber`을 사용하지 않는 방법이 있어서 어떤 변수인지 여쭤보신 걸까요?

2022-08-06 12:12 UTC, 0-Chan commented on src/index.js
> +  function calculate(number1, number2, symbol) {
매개 변수가 많아질 때 불편함은...
- 매개변수 위치에 꼭 맞춰야 함.<br> : Object를 매개변수로 하면 자리에 크게 신경 쓰지 않아도 됨.
- 함수를 호출 할 때 알아보기가 힘들다.<br> : 기존에 foo(true, false) 라고 하면 각 값이 무슨 뜻인지 알 수 없었지만 object를 쓰면 좀 더 직관적이다. 

그 외에도 기존에 단일 값만 받는 return에 object를 넘겨 여러 개의 값을 return 할 수도 있습니다!

2022-08-06 12:37 UTC, daadaadaah reviewed
버그 수정 화이팅하시구~👊 내일 PR 기다리고 있을게요!

> 혹시 previousNumber을 사용하지 않는 방법이 있어서 어떤 변수인지 여쭤보신 걸까요?
아니요! 그냥 궁금해서 여쭤봤어요!ㅎㅎ

2022-08-07 12:57 UTC, 0-Chan commented
> 버그 수정 화이팅하시구~fist_oncoming 내일 PR 기다리고 있을게요!
> 
> > 혹시 previousNumber을 사용하지 않는 방법이 있어서 어떤 변수인지 여쭤보신 걸까요?
> > 아니요! 그냥 궁금해서 여쭤봤어요!ㅎㅎ

마지막 PR 드립니다..!
코드를 억지로 짜맞춰서 버그를 수정한 느낌입니다..ㅜㅜ

다 하고 풀이를 보고나서야 제가 놓치고 있었던 부분이 무엇이었는지 깨달았습니다!
첫 번째 주 꾸준히 코드 리뷰 해주셔서 감사하구요 ㅎㅎ
주간 회고는 디스코드 채널에 올려놓도록 하겠습니다!

2022-08-08 02:30 UTC, daadaadaah commented
> 다 하고 풀이를 보고나서야 제가 놓치고 있었던 부분이 무엇이었는지 깨달았습니다! 첫 번째 주 꾸준히 코드 리뷰 해주셔서 감사하구요 ㅎㅎ 주간 회고는 디스코드 채널에 올려놓도록 하겠습니다!

풀이를 보고 나서 스스로 깨달은 것도 잘하신거예요!👍 이번주도 수고하셨습니다🚀

2022-08-08 06:22 UTC, merged