계산기 구현
CodeSoom/week1-assignment-2 pull request #169
Opened 2022-08-03 17:07 UTC by violet4795

let 제거에서 아이디어를 얻어서
render에 몇몇 값 처리하는 함수를 얹어서 구현했습니다.

2022-08-04 13:52 UTC, daadaadaah requested changes
let 제거에서 아이디어를 얻어 구현하신 점 잘하셨어요!👍
render를 callback으로 내려준 것도 신선했구요!ㅎㅎ
몇가지 코멘트 남겨드렸습니다!ㅎㅎ다음 PR 기다리고 있을게요!ㅎㅎ

2022-08-04 13:52 UTC, daadaadaah commented on src/index.js
> +  }
switch문은 대표적으로 코드 가독성이 좋지 않은 표현이예요! switch 문을 사용하지 않고 문제를 해결할 수 있는 방법은 없을까요?
가동성이 좋지 않은 코드에 대해 더 공부해보고 싶으시면, [클린코드](http://www.yes24.com/Product/Goods/11681152) 같은 도서 한번 읽어보시면 도움이 되실 거예요!

2022-08-04 13:52 UTC, daadaadaah commented on src/index.js
> +function calc(calcResult, operator, currentNumber) {
매개변수명, 함수명을 축약형보다 full Name으로 표현해주시는게 더 좋아요!

2022-08-04 13:52 UTC, daadaadaah commented on src/index.js
> +function clickNumber(calcResult, operator, currentNumber, number, callBackFunc) {
여기서, `number`가 버튼을 클릭했을 때의 숫자 인 것 같은데, `currentNumber` 의미가 현재 숫자라서 둘이 헷갈립니다! `number`를 좀더 의도가 드러나는 표현을 써보시는건 어떤가요?

2022-08-04 13:52 UTC, daadaadaah commented on src/index.js
> +function clickOperator(calcResult, operator, currentNumber, operatorString, callBackFunc) {
lint 에러 때문에 callbackFunc을 사용하신 것 같은데, lint 에러를 해결하는 다른 방법은 없을까요?(힌트 : 함수는 함수 안에 또다른 함수를 정의할 수 있다!)

2022-08-04 13:52 UTC, daadaadaah commented on src/index.js
> +  callBackFunc(calcResult, operator, isExistCurrentNumber(currentNumber) ? Number(`${currentNumber}${number}`) : number);
함수의 매개변수에 계산된 결과값을 넣어주는게 가독성 측면에서 더 좋은 것 같아요!ㅎㅎ

2022-08-04 15:16 UTC, violet4795 commented on src/index.js
> +  callBackFunc(calcResult, operator, isExistCurrentNumber(currentNumber) ? Number(`${currentNumber}${number}`) : number);
넵 그런거같습니다!

2022-08-05 13:13 UTC, daadaadaah requested changes
함수를 잘게 잘 쪼개주시고 변수명도 명확해서 읽기 좋았습니다!ㅎㅎ

몇가지 코멘트 남겨드렸는데, 참고하시고 PR 또 날려주세요🚀

2022-08-05 13:13 UTC, daadaadaah commented on src/index.js
> +function render(...calculateParameter) {
여러 개의 매개변수가 필요할 때에는 [RORO 패턴](https://usecode.pw/elegant-patterns-in-modern-java-script-roro/) 을 한번 활용해보세요! 그러면, 주석이 필요 없어지고 의도가 좀더 명확히 드러날 겁니다!ㅎㅎ

2022-08-05 13:13 UTC, daadaadaah commented on src/index.js
> +  function addNumber(clickedNumber, currentNumber) {
숫자를 만들어주는 함수이므로, getNumber나 makeNumber 네이밍은 어떠신가요?
addNumber 라고해서 1+1 이렇게 숫자를 더하는 함수처럼 생각할 수도 있을 것 같아요!

2022-08-05 13:13 UTC, daadaadaah commented on src/index.js
> +    return render(calculatedNumber, operator, calculatedCurrentNumber);
render를 return 해주시는 이유가 궁금합니다!ㅎㅎ(53번째 줄도 마찬가지로요!)

2022-08-05 13:13 UTC, daadaadaah commented on src/index.js
> +      <p>{settingShowNumber(calculateParameter[0], calculateParameter[2])}</p>
함수 호출보다 어떤 상태값을 하나 더 만들어서 변수로 최종 결과를 보여주는 건 어떠신가요?ㅎㅎ

2022-08-05 13:13 UTC, daadaadaah commented on src/index.js
> +    return currentNumber; // '='
객체를 활용해서 계산해주는 방법에 대해 한번 도전해봅시당!ㅎㅎ

2022-08-05 15:28 UTC, violet4795 commented on src/index.js
> +function render(...calculateParameter) {
render 함수 스코프에서 처음엔 {  calculatedNumber, operator, currentNumber }
이렇게 받아보려했는데,
같은의미의 변수가 여러개 되버리니 처리가 쉽지않네요.
클래스로 스코프를 나눠서 처리해보겠습니다

2022-08-06 12:04 UTC, daadaadaah approved these changes
클래스로 만드셔서 문제를 해결하셨군요!👍
피드백 강의를 통해 과연 아샬님은 어떻게 문제를 해결하셨는지 한번 잘 관찰해보세요!

2022-08-08 06:22 UTC, merged