1주차 과제 2 -> 간단한 사칙 연산 계산기 구현
CodeSoom/week1-assignment-2 pull request #170
Opened 2022-08-04 11:58 UTC by xunxee

1. 과제 2의 기본적인 UI를 만들었습니다.
2. render 함수의 매개변수를 이용하여
  그 안의 중첩 함수들을 이용해 숫자를 누를 때마다
  resultNumber를 변경시켜 클릭한 숫자를 반영하도록 만들었습니다.
3. 아직 전반적인 것들을 완성하지 못해 과제의 기준을 모두 만족시키지 못했지만
  commit을 남겨봅니다.

2022-08-04 13:24 UTC, daadaadaah requested changes
과제 완성은 못하셨지만, PR 날려주신 점 너무 좋습니다!👍
변수명 전반적으로 너무 깔끔해서 읽기 너무 좋았어요!
다음 PR 기다리고 있을게요~ㅎㅎ

2022-08-04 13:24 UTC, daadaadaah commented on src/index.js
> +  function clickSymbol(symbol) {
`symbol` 이란 단어는 자바스크립트에서의 symbol이랑 혼동을 줄 것 같아요! 다른 단어로 표현해봅시당!ㅎㅎ

2022-08-04 13:24 UTC, daadaadaah commented on src/index.js
> +    if (firstNumber === 0 && operation === 'empty') render(firstNumber + number, secondNumber, resultNumber + number, operation);
if문의 중괄호는 생략 가능하더라도 명시적으로 기재주는 것이 가독성 측면에서 더 좋아요!

2022-08-04 13:24 UTC, daadaadaah commented on src/index.js
> +function render(firstNumber = 0, secondNumber = 0, resultNumber = 0, operation = 'empty') {
operation에 `empty` 대신 `''` 빈문자열로 했을 때, xunxee 의 의도하신 것과 의미가 달라질까요?

2022-08-05 04:51 UTC, xunxee commented on src/index.js
> +  function clickSymbol(symbol) {
앗 맞습니당! 심볼이 JS에서의 symbol과 혼동을 줄 수 있는 것 같습니다 😆

2022-08-05 04:52 UTC, xunxee commented on src/index.js
> +    if (firstNumber === 0 && operation === 'empty') render(firstNumber + number, secondNumber, resultNumber + number, operation);
단순하게 최대한 짧게 줄이는 것이 가독성에 좋다고 생각했던 것 같습니당!
리뷰 반영해서,
명시적으로 중괄호를 넣어보니 가독성이 더 있는 것 같내용
감사합니다🙏🏼

2022-08-05 05:50 UTC, xunxee commented on src/index.js
> +function render(firstNumber = 0, secondNumber = 0, resultNumber = 0, operation = 'empty') {
빈 문자열이다보니,
제가 넣은 empty와 결국 같은 의미이군요!
empty보다 ''이 의미가 더 명확하고, 한 눈에 들어오는 것 같아요🙏🏼

2022-08-05 13:20 UTC, daadaadaah requested changes
if문이 많고, 중첩도 많은 코드는 대표적으로 코드 가독성이 좋지 않은 표현이예요! if 문을 사용하지 않고 문제를 해결할 수 있는 방법은 없을까요? 객체나 또는 함수를 이용해서 뽑아낼수 있는 부분은 뽑아내는게 더 좋을 것 같아요!ㅎㅎ

가동성이 좋지 않은 코드에 대해 더 공부해보고 싶으시면, [클린코드](http://www.yes24.com/Product/Goods/11681152) 같은 도서 한번 읽어보시면 도움이 되실 거예요!

2022-08-05 13:20 UTC, daadaadaah commented on src/index.js
> +/* eslint no-use-before-define: ["error", { "functions": false }] */
주석 제거해줘도 괜찮지 않을까요?ㅎㅎ

2022-08-05 13:20 UTC, daadaadaah commented on src/index.js
> +  function clickSymbol(sign) {
함수 이름도 Sign으로 바꿔주는게 좋을 것 같아요!ㅎㅎ

2022-08-06 13:07 UTC, xunxee commented on src/index.js
> +  function clickSymbol(sign) {
리뷰 반영했습니다!
감사합니다 ㅎㅎ

2022-08-08 06:22 UTC, merged