1차 제출 간단한 사칙 연산 계산기 구현
CodeSoom/week1-assignment-2 pull request #171
Opened 2022-08-04 11:58 UTC by ChoJinmok

2022-08-04 13:16 UTC, daadaadaah requested changes
- `handleOperatorClick` 내부 로직이 많이 복잡한대, let 제거하시면서 로직 좀 수정될 수 있으니, 그떄 다시 한번 볼게요~ㅎㅎ

> calculator 함수에 eslint에서 함수 마지막에 무조건 return을 해주라는 에러가 떠서 reult 변수를 만들어 주고 반환해줬는데 이게 맞을까요?

- switch 문을 사용하지 않고 다른 방법으로 문제를 해결한다면, 같이 해결될 문제인 것 같아요!

2022-08-04 13:16 UTC, daadaadaah commented on src/index.js
> +  return result;
switch문은 대표적으로 코드 가독성이 좋지 않은 표현이예요! switch 문을 사용하지 않고 코드를 표현할 수 있는 방법이 있을까요? 
가동성이 좋지 않은 코드에 대해 더 공부해보고 싶으시면, [클린코드](http://www.yes24.com/Product/Goods/11681152) 같은 도서 한번 읽어보시면 도움이 되실 거예요!

2022-08-04 13:16 UTC, daadaadaah commented on src/index.js
> +function calculator(operator, ...number) {
매개변수가 점점 많아지면 어떤 불편함이 있을까요?
[RORO 패턴](https://usecode.pw/elegant-patterns-in-modern-java-script-roro/) 에 대해 한번 공부해봅시당!

2022-08-04 13:16 UTC, daadaadaah commented on src/index.js
> +          <button type="button" onClick={() => handleNumClick(item)}>
`item`보다 좀더 의도가 드러나는 표현은 없을까요? 🤔

2022-08-04 13:16 UTC, daadaadaah commented on src/index.js
> +          <button type="button" onClick={() => handleOperatorClick(item)}>
`item`보다 좀더 의도가 드러나는 표현은 없을까요? 🤔

2022-08-04 13:16 UTC, daadaadaah commented on src/index.js
> +  }
if ~ else 구조는 코드 가독성이 좋지 않아서 사용을 권장하지 않아요!
[guard clauses](https://www.refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html) 에 대해 한번 공부해봅시당!ㅎㅎ

2022-08-05 06:57 UTC, ChoJinmok commented on src/index.js
> +  return result;
밑에 언급하신 guard courses로 바꾸니까 훨씬 가독성이 좋네요!! 좋은 리뷰 감사합니다!!👏

2022-08-05 08:52 UTC, ChoJinmok commented on src/index.js
> +function calculator(operator, ...number) {
RORO 패턴..! 좋은 리뷰 감사드립니다🙂

2022-08-05 08:57 UTC, ChoJinmok commented on src/index.js
> +          <button type="button" onClick={() => handleNumClick(item)}>
9시에 급하게 하느라 확인을 못하고 푸쉬를 했네요 😭 리뷰 감사합니다!!

2022-08-05 08:57 UTC, ChoJinmok commented on src/index.js
> +          <button type="button" onClick={() => handleOperatorClick(item)}>
리뷰 감사합니당!!ㅎㅎ

2022-08-05 09:58 UTC, ChoJinmok commented on src/index.js
> +  }
Guard Clauses라는 해결책이 있군요?! 코드가 가독성이 확실히 좋아보입니다!!
좋은 리뷰 감사합니다!!ㅎㅎ 진짜 발전하는 기분이 드는 거 같네요🙂

2022-08-05 13:07 UTC, ChoJinmok reviewed
리뷰 펜딩중신지 모르고 커밋을 더 해버렸습니다 ㅠㅠ 죄송합니다

2022-08-05 13:34 UTC, daadaadaah commented
작업 계속 하고 계신건가요?ㅎㅎ

2022-08-05 13:36 UTC, daadaadaah commented on src/index.js
> +  throw new Error('Wrong Operator!');
객체를 활용해 구현하는 방법에 대해 한번 도전해봅시당!ㅎㅎ

2022-08-05 13:36 UTC, daadaadaah commented on src/index.js
> +    const resultNumber = leftOperatedNumber ? Number(`${leftOperatedNumber}${number}`) : number;
맥락구분을 위해 한줄 띄어줍시당!ㅎㅎ

2022-08-05 13:36 UTC, daadaadaah commented on src/index.js
> +        currentNumber, leftOperatedNumber, rightOperatedNumber, currentOperator: operator !== '=' && operator,
`operator !== '=' && operator` 이 부분 함수로 빼서 return 값을 매개변수로 넣어주시는 건 어떠신가요?

2022-08-05 13:36 UTC, daadaadaah commented on src/index.js
> +      render({
맥락 구분을 위해 한줄 띄어주는게 좋아요! 다른 부분도 마찬가지로 적용시켜주세요!ㅎㅎ

2022-08-05 13:36 UTC, daadaadaah commented on src/index.js
> +  function handleOperatorClick(operator) {
이 함수 너무 무겁고 if 문이 너무 많아서 가독성이 좋지 않은 것 같아요!ㅎㅎ
함수로 추출할 수 있는 부분이 없을까? 에 대해 한번 생각해보시면 좋을 것 같아요!ㅎㅎ

2022-08-05 13:37 UTC, daadaadaah requested changes
PR을 보내고 작업중이시면, 코멘트 남겨주시는게 좋을 것 같아요!ㅎㅎ

2022-08-05 13:51 UTC, ChoJinmok commented on src/index.js
> +    const resultNumber = leftOperatedNumber ? Number(`${leftOperatedNumber}${number}`) : number;
띄워주니 가독성이 훨씬 좋네요!🙂

2022-08-05 13:52 UTC, ChoJinmok commented on src/index.js
> +      render({
리뷰 감사합니다!~🙏

2022-08-05 14:05 UTC, ChoJinmok commented on src/index.js
> +        currentNumber, leftOperatedNumber, rightOperatedNumber, currentOperator: operator !== '=' && operator,
좋은 리뷰 감사합니다 ㅎㅎ

2022-08-06 01:24 UTC, ChoJinmok commented on src/index.js
> +  throw new Error('Wrong Operator!');
그렇네요!? 특정값일 때 어떤 값이 나오게 하려면 조건문보다는 객체가 훨씬 좋은 로직 같습니다!👍

2022-08-06 01:49 UTC, ChoJinmok reviewed
죄송합니당 😭 깃으로 협업한 적이 많지 않다보니... 깃으로 소통하는 법까지 배우는 거 같아서~ 감사합니다!!

2022-08-06 02:11 UTC, ChoJinmok commented on src/index.js
> +  function handleOperatorClick(operator) {
안그래도~ 가독성이 너무 좋지 않아서 고민했었는데~🥲
조건에 따라 함수 추출하는게 맞을까요?~ 조건에따라 함수를 추출해서 사용하니까 가독서이 전보다는 좋아지는 것 같습니다!👏

2022-08-06 13:34 UTC, daadaadaah reviewed
음..아샬님의 피드백 강의를 보면, 굉장히 간단하게 구현하신걸 볼 수 있을 거예요!
보시고 내 코드에 적용해볼만한 것들이 없나 한번 생각해보시는게 좋을 것 같아요!ㅎㅎ
한번 고민해보시고, 수정이 필요하다 싶으시면, PR 날려주세요~

2022-08-08 06:22 UTC, merged

2022-08-08 07:57 UTC, ChoJinmok reviewed
아샬님 코드 보니까 트레이너님이 리뷰를 남기신 방향에대해 알겠네요!!ㅎㅎ
한주동안 좋은 리뷰 감사드립니다!!