make calculator
CodeSoom/week1-assignment-2 pull request #177
Opened 2022-10-11 11:29 UTC by yxxnhx

간단한 계산기 만들기를 진행하였습니다.
매일 올리는 것이 좋다고 하여서 현재는 틀만 잡은 채로 어떻게하면 계산기를 만들 수 있을지 고민하고 있습니다.
버튼을 하나하나 value 값을 지정해서 그 값을 받아오는 것이 좋은 것인지 아니면 수업시간에 했던 것처럼 map을 돌면서 i 값을 받아오는 것이 좋은지 잘 모르겠습니다.
선택한 숫자자를 어떻게하면 result에 넣을 수 있을지도 조금 더 고민해야겠습니다

2022-10-12 02:39 UTC, daadaadaah commented
틀만 잡아놓으셨는데, 시작이 좋은 것 같아요!ㅎㅎ다음 PR 기다리고 있을게요!ㅎㅎ
> 버튼을 하나하나 value 값을 지정해서 그 값을 받아오는 것이 좋은 것인지 아니면 수업시간에 했던 것처럼 map을 돌면서 i 값을 받아오는 것이 좋은지 잘 모르겠습니다.

- 코드숨 교육기간 동안 최대한 아샬님의 방식을 그대로 따라해보는걸 추천드려요!ㅎㅎ

2022-10-13 03:52 UTC, daadaadaah requested changes
질문주신 내용은 [`handleNum`에 남긴 코멘트](https://github.com/CodeSoom/react-week1-assignment-2/pull/177#discussion_r994087739)를 참고하시면 해결 될 것 같아요!ㅎㅎ
다음 PR 기다리고 있습니당!😊

2022-10-13 03:52 UTC, daadaadaah commented on src/index.js
> +  function handleNum({ number }) {
여기서 number는 언제 사용하는 매개변수인가용?ㅎㅎ

2022-10-13 03:52 UTC, daadaadaah commented on src/index.js
> +  function handleSum({ operator }) {
맥락 구분을 위해 한줄 띄어줍시당!ㅎㅎ

2022-10-13 03:52 UTC, daadaadaah commented on src/index.js
> +          <button type="button" onClick={() => handleSum(operator)}>
`handleSum`의 매개변수의 선언형태와 사용형태가 다릅니다!ㅎㅎ한번 체크해주세요!ㅎㅎ

2022-10-13 03:55 UTC, daadaadaah commented on src/index.js
> +const operatorArray = ['+', '-', '*', '/', '='];
변수명에 Array, Object 등을 직접 기재해주기보다 `numbers`나 `operators`등으로 복수로 표현해주셔도 될 것 같아요!ㅎㅎ

2022-10-13 03:55 UTC, daadaadaah commented on src/index.js
> +  '': (x, y) => x || y,
빈값은 언제 사용되는 건가용?ㅎㅎ

2022-10-13 09:29 UTC, yxxnhx commented on src/index.js
> +  function handleNum({ number }) {
누른 값을 받아오려고 지정한 변수인데 필요가 없는 것인가요? 그렇다면 한번 지우고 진행해보겠습니다

2022-10-13 09:29 UTC, yxxnhx commented on src/index.js
> +  function handleSum({ operator }) {
넵 반영해서 수정하겠습니다!

2022-10-13 09:29 UTC, yxxnhx commented on src/index.js
> +          <button type="button" onClick={() => handleSum(operator)}>
앗 그렇군요 한번 수정해보겠습니다!

2022-10-13 09:30 UTC, yxxnhx commented on src/index.js
> +const operatorArray = ['+', '-', '*', '/', '='];
아하 넵 변수명 변경하겠습니다!

2022-10-13 11:35 UTC, yxxnhx commented on src/index.js
> +  function handleNum(value) {
여기서 num의 기본값을 0으로 지정하였기 때문에 누른 값을 추가해주기 위해서는 곱하기를 하여 선택한 value가 들어가기 위하여 10을 곱해야 한다고 하는데 왜 10을 곱해야만 할까요? 0에는 무엇이든 곱해도 0이 나오기 때문에 상관이 없지 않을까요? 그리고 그냥 곱하지 않고 그냥 바로value를 넣으면 오류는 나지 않는데 왜 곱해야 할까요?

2022-10-13 11:39 UTC, yxxnhx commented
<img width="764" alt="image" src="https://user-images.githubusercontent.com/50559373/195586703-f0062c32-4567-4b08-9134-1f50645b496e.png">

여기서 num의 기본값을 0으로 지정하였기 때문에 누른 값을 추가해주기 위해서는 곱하기를 하여 선택한 value가 들어가기 위하여 10을 곱해야 한다고 하는데 왜 10을 곱해야만 할까요? 
0에는 무엇이든 곱해도 0이 나오기 때문에 상관이 없지 않을까요? 
그리고 그냥 곱하지 않고 그냥 바로 value를 넣으면 오류는 나지 않는데 왜 곱해야 할까요?

2022-10-13 11:44 UTC, yxxnhx commented on src/index.js
> +  '': (x, y) => x || y,
처음에는 이 빈값이 사실은 +, -, *, / 부분을 칠 때 형식이 똑같으니 계속 복사 붙여넣기 하다가 미처 지우지 못하고 남긴 부분이어서 지웠습니다
<img width="526" alt="image" src="https://user-images.githubusercontent.com/50559373/195586934-8a914d28-0ef0-490b-b9c5-92ba9ca8ca94.png">

그랬더니 계속 이와같은 오류가 나서 다시 처음부터 되돌려서 npm start를 해보니 함수가 아니라는 오류는 나오지는 않습니다 그냥 조금 이상하게 계산이 돼요
빈값이 필수적으로 필요한 것일까요? 그렇다면 이유가 무엇인지 궁금합니다

![Oct-13-2022 20-43-03](https://user-images.githubusercontent.com/50559373/195587445-18f4d6a3-c08c-43ff-9a25-91c603bd8726.gif)

2022-10-14 07:02 UTC, daadaadaah commented on src/index.js
> +  '': (x, y) => x || y,
빈값 없이도 구현은 가능할 것 같아요!

>  함수가 아니라는 오류는 나오지는 않습니다 그냥 조금 이상하게 계산이 돼요
- 이상하게 계산되는게 어떻게 이상하게 계산되는지, 왜 이상하게 계산되는지 콘솔을 하나하나 찍어보며 확인해보는 걸 추천드려요!ㅎㅎ

2022-10-14 08:25 UTC, daadaadaah requested changes
> 여기서 num의 기본값을 0으로 지정하였기 때문에 누른 값을 추가해주기 위해서는 곱하기를 하여 선택한 value가 들어가기 위하여 10을 곱해야 한다고 하는데 왜 10을 곱해야만 할까요?
0에는 무엇이든 곱해도 0이 나오기 때문에 상관이 없지 않을까요?
그리고 그냥 곱하지 않고 그냥 바로 value를 넣으면 오류는 나지 않는데 왜 곱해야 할까요?

혹시, 11, 123 이렇게 입력해보셨나요? ㅎㅎ

2022-10-14 08:25 UTC, daadaadaah commented on src/index.js
> +function calculate(num, otherNum, currentOperator) {
`num`, `otherNum` 보다 좀더 의도가 드러나는 변수명은 없을까요?

2022-10-14 08:25 UTC, daadaadaah commented on src/index.js
> +  function handleSum(value) {
`value` 보다 좀더 의도가 드러나는 변수명은 없을까요?

2022-10-14 10:27 UTC, yxxnhx commented on src/index.js
> +  '': (x, y) => x || y,
빈값이 없이도 구현이 가능한가요? 음.. 그렇다면 calculation을 다시 한번 짜보겠습니다 없으면 계속 오류가 나네요ㅠㅠ

2022-10-14 10:28 UTC, yxxnhx commented on src/index.js
> +function calculate(num, otherNum, currentOperator) {
한번 변경해보겠습니다

2022-10-14 10:28 UTC, yxxnhx commented on src/index.js
> +  function handleSum(value) {
네 의도가 드러나게 한번 변경해보겠습니다!

2022-10-15 03:42 UTC, daadaadaah reviewed
> 그리고 빈값 없이도 오류가 나지 않게 하실 수 있다고 하여서 변경을 해보았는데 지금 연산자가 아예 작동을 하지 않아 고민입니다
콘솔에 찍어보면 누른 연산자가 콘솔에 찍히기는 하지만 calcultation 함수가 문제인 것인지 에러는 나지 않지만 작동을 하지 않네요
혹시 제 접근법이 잘못된 것일까요? 다른 방법으로 더 찾아봐야 할까요?

- 콘솔을 어디서 어떻게 찍었는지 스샷 찍어저 보여주실 수 있나요?
- 저라면 아래처럼 찍어보면서, 각 함수마다 변수명들이 어떻게 바뀌는지 추척하면서 문제를 해결할 것 같거든용!ㅎㅎ
- 추가로, 저라면, 빈값 없이 `handleSum` 함수에서 문제를 해결해 볼 것 같아요!
<img width="653" alt="스크린샷 2022-10-15 오후 12 42 18" src="https://user-images.githubusercontent.com/60481383/195967331-0d17abd2-1a98-48d5-8bf9-f8d7a0bfc36a.png">

2022-10-15 03:42 UTC, daadaadaah commented on src/index.js
> +function calculate(accumulateNumber, currentNumber, currentOperator) {
변수명을 형용사+명사 또는 수동태+명사 이런 형태로 작성해보시는 건 어떠신가요? 이런식으로 하면, `함수`랑 `변수`랑 구분하기 좋더라구요! 
지금 `accumulateNumber`을 보고 사용할 떄 헷갈리수 있을 것 같아요!
그리고, 42번째 줄에서도 동일한 변수명을 사용하셨는데, 둘이 구분할 수 있도록 바꿔주시는게 좋을 것 같아요!ㅎㅎ

2022-10-15 07:21 UTC, yxxnhx commented on src/index.js
> +  '': (x, y) => x || y,
<img width="525" alt="스크린샷 2022-10-15 오후 2 58 10" src="https://user-images.githubusercontent.com/50559373/195974558-80d3af3f-adbe-494f-8f51-a3dd16690fac.png">

빈값이 없다면 위와 같은 오류가 계속 납니다 초기값을 설정해준 것이라고 생각을 하는데 초기값 없이도 가능한 방법이 있나요?

2022-10-15 07:22 UTC, yxxnhx commented on src/index.js
> +function calculate(accumulateNumber, currentNumber, currentOperator) {
네 수동태로 변경해보겠습니다

2022-10-16 01:21 UTC, daadaadaah requested changes
> 1. 그리고 이전에 빈값이 없이도 구현이 가능하다고 하여 빈값을 지운채로 진행을 하면 계속 동일한 오류가 나네요. 제가 생각하기에는 빈값은 초기값을 설정해주기 위하여 필수적으로 필요한 것 같습니다. 만약 빈값이 없다면 그냥 연산자별로 if else if로 calculate 함수를 새로 짜는 것이 좋을까요? 그렇게하면 코드가 너무 길어지고 더러워질 것 같아서 옳은 방법이 아니라고 생각이 들긴 합니다.

- 아샬님은 빈값이 없이 어떻게 구현하셨는지 피드백 강의를 통해 한번 참고해보세요!ㅎㅎ

> 2. 빈값을 살려둔 채로 구현을 하면 계산이 되긴 하는데 두번째로 누른 숫자 값이 다음과 같이 콘솔에 찍히기는 하지만 화면에 출력이 되지 않습니다. 왜 그런 것일까요? 값이 나올 곳에
{accumulatedNumber || resultNumber}
이렇게 모두 찍히게 설정을 하였는데 왜 그런 것일까요? 

- `{accumulatedNumber || resultNumber} ` 이 부분 혹시, 코드 의도가 `accumulatedNumber`이거나 `resultNumber`을 보여라의 의도로 작성하신 건가요? `||` 연산자는 언제 사용되는 연산자일까요?

2022-10-16 23:48 UTC, daadaadaah approved these changes

2022-10-16 23:48 UTC, daadaadaah commented on src/index.js
> +  }
다음 과제에서는 맥락 구분을 위해 함수들 사이사이 한줄 씩 띄어줍시당!ㅎㅎ

2022-10-16 23:49 UTC, daadaadaah commented
한주동안 수고 많으셨습니당!ㅎㅎ다음 과제도 같이 힘내봐용!👊

2022-10-17 09:49 UTC, merged