1주차 과제 - 간단 계산기 만들기
CodeSoom/week1-assignment-2 pull request #178
Opened 2022-10-12 11:17 UTC by sejineeee

## 내용
map 메서드를 이용해서 숫자 버튼을 구현하였습니다.
연산자와 메서드를 객체로 만들어서 `keys()` 메서드를 이용해서 연산자 버튼을 구현하였습니다.

## 질문
1. 숫자를 연속해서 누르면 숫자가 더해져서 출력되어야 한다고 하는데, 숫자 값을 저장한 형태를 만들고 싶은데, 어떤 식으로 구현하면 좋을지 잘 모르겠습니다.
2. 재귀함수에 대해 이해가 부족한 상태여서, 혹시, 이 과제에서도 재귀함수를 이용해야 구현을 할 수 있을까요?
3. 숫자 값이나 결과 값을 저장해야 된다면 객체 안에 담아야 된다고 생각해서 `state`라는 객체를 만들었는데요. 값을 받아와서 저장을 해주기 위해서는 이런 식으로 접근하는 방식이 맞을까요?

2022-10-13 05:09 UTC, daadaadaah requested changes
> 1. 재귀함수에 대해 이해가 부족한 상태여서, 혹시, 이 과제에서도 재귀함수를 이용해야 구현을 할 수 있을까요?
> 2. 숫자를 연속해서 누르면 숫자가 더해져서 출력되어야 한다고 하는데, 숫자 값을 저장한 형태를 만들고 싶은데, 어떤 식으로 구현하면 좋을지 잘 모르겠습니다.
> 3. 숫자 값이나 결과 값을 저장해야 된다면 객체 안에 담아야 된다고 생각해서 state라는 객체를 만들었는데요. 값을 받아와서 저장을 해주기 위해서는 이런 식으로 접근하는 방식이 맞을까요?

- 혹시, 과제1에서 했던 방식을 활용하는 방법을 시도해보셨나요?ㅎㅎ어려운 개념(예 : 재귀함수)을 사용해서 문제해결을 하기보다 자신이 아는 방법을 활용해보는 걸 추천드립니다!ㅎㅎ혹시나 도움이 필요하시면, 코멘트 남겨주세요!😊

2022-10-13 05:11 UTC, daadaadaah commented on src/index.js
> +            Object.keys(calculate).map((operator) => <button type="button" onClick={() => calculate[operator]()}>{operator}</button>)
오! 제가 과제했을 때에는 Object.keys를 활용할 생각을 못했는데, 잘하셨어요!👏👏

2022-10-13 11:59 UTC, sejineeee commented
[e6534ae](https://github.com/CodeSoom/react-week1-assignment-2/pull/178/commits/e6534aed2eec694c0215cdfaaba81eddfd91c388) 연산자 버튼을 눌렀을 때 연산자를 가져올 수 있는 함수를 새로 구현하였고, 그러면서 `calculate` 객체에 함수를 분리하였습니다.

숫자를 클릭했을 때, 처음에 숫자를 할당해주고, 두번째 누른 숫자를 또 할당해주고 싶었으나, 처음에 할당한 숫자가 두 번째 숫자로 바뀌어서... 이 부분은 어떻게 담아야 될 지 좀 더 생각해봐야 되겠습니다.

2022-10-14 06:51 UTC, daadaadaah requested changes
> 숫자를 클릭했을 때, 처음에 숫자를 할당해주고, 두번째 누른 숫자를 또 할당해주고 싶었으나, 처음에 할당한 숫자가 두 번째 숫자로 바뀌어서... 이 부분은 어떻게 담아야 될 지 좀 더 생각해봐야 될 것 같습니다!!
무엇을 모르는지 잘 모르다 보니, 많이 고민해보고 많이 질문하도록 하겠습니다! 감사합니다~😄

- 좋습니당!ㅎㅎ"왜 처음에 할당한 숫자가 두번째 숫자로 바뀌는지"에 대해 콘솔로 하나하나 찍어보면서 실험해보세요!ㅎㅎ변수들을 여기에도 넣어봤다 저기에도 넣어봤다 등등 다양한 실험을 해보다보면 많은 걸 배우시게 될거예용ㅎㅎ다음 PR 기다리고 있을게용ㅎㅎ

2022-10-14 06:51 UTC, daadaadaah commented on src/index.js
> +  };
console 때문에 따로 뺴주신건가용?ㅎㅎ

2022-10-14 06:51 UTC, daadaadaah commented on src/index.js
> +  };
count는 render 함수의 매개변수로 관리하시고, 그 외의 값들은 render 함수의 내부 변수로 관리하시는데, 어떤 기준으로 나누셨는지 궁금합니다!ㅎㅎ

2022-10-14 09:02 UTC, sejineeee commented on src/index.js
> +  };
만약 연산 함수를 다른데서 사용할 경우를 생각해서 분리하는 게 어떨까 생각이 들어 시도해보았습니다. 분리하지 않는 게 가독성도 더 좋고, 유지보수 측면에서도 어떤 지 멘토님의 생각이 궁금합니다! 🙂

2022-10-14 09:04 UTC, sejineeee commented on src/index.js
> +  };
이 경우는 다양한 시도를 하다 보니, 아직 방향성을 찾지 못 하여 이런 형태로 작성하게 되었습니다. 이러한 부분에 대해서 고민해보고 수정하도록 하겠습니다!!

2022-10-14 12:01 UTC, sejineeee commented
[11cd953](https://github.com/CodeSoom/react-week1-assignment-2/pull/178/commits/11cd953b31e60c0d621b42f62f9ce50ed5f2f406) 

https://user-images.githubusercontent.com/86041335/195841477-d2042796-38a6-4da4-895e-02c776e1eb7a.mov


연산 함수를 처음에는 객체로 할당했다가, 따로 분리를 했다가, 다시 객체로 변경하였습니다.
외부에서 선언했었던 변수는 불필요하다고 생각하여 render 함수 내부에서 `state`변수를 선언하였습니다.

`=` 버튼을 눌렀을 때 값이 담기도록 해주고 싶은데, 좀 더 고민해봐야 될 것 같습니다.
그리고 값을 저장할 수 있도록 `state` 객체에 `key`를 하나 더 선언해야 구현이 가능할지, 지금 state 형태에서도 구현이 가능할지 잘 모르겠습니다.

`prevNumber`라고 이름을 지은 것은 처음에는 prevNumber, nextNumber의 형태로 해주려고 했는데, 고치다 보니 prevNumber가 남았습니다. 이 부분은 이름을 고려한 뒤 수정을 하도록 하겠습니다!! 🙇

2022-10-15 03:13 UTC, daadaadaah requested changes
오! 코드 정말 깔끔하네요!
state 변수 없이 render 함수의 매개변수를 사용하는 방법로는 문제가 해결이 안되는 건가요?ㅎㅎ

2022-10-15 03:13 UTC, daadaadaah commented on src/index.js
> +function render(number, operator) {
매개변수가 점점 많아지면 어떤 불편함이 있을까요? 관련해서 [RORO 패턴](https://usecode.pw/elegant-patterns-in-modern-java-script-roro/)에 대해 공부해보시는 걸 추천드려요!ㅎㅎ

2022-10-15 03:14 UTC, daadaadaah commented on src/index.js
> +function render(number, operator) {
매개변수가 점점 많아지면 어떤 불편함이 있을까요? 관련해서 [RORO 패턴](https://usecode.pw/elegant-patterns-in-modern-java-script-roro/)에 대해 공부해보시는 걸 추천드려요!ㅎㅎ

2022-10-15 07:52 UTC, sejineeee commented
[9f047d8](https://github.com/CodeSoom/react-week1-assignment-2/pull/178/commits/9f047d8dfe68475797ab0613459e08d092e80066) render 함수 내부에서 state 객체 선언 없이 매개변수를 이용하도록 수정하였습니다.
하지만 그에 따라서 오류가 발생하여 그 부분이 많이 고민됩니다. 
`handleClickNumber` 함수에서 조건문에서 실행한 render 함수에 인자를 전달하는 부분에서 다시 수정을 해야 된다고 생각이 듭니다.
아직 구현이 제대로 되지 않다 보니, 어느 부분을 질문해야 될 지 잘 모르겠습니다...ㅎㅎㅎ 이번주 코드 리뷰도 감사드립니다!👊🏻

2022-10-16 01:12 UTC, daadaadaah requested changes
지금 render 함수 선언된 매개변수와 사용되는 매개변수가 다릅니다! 에러 해결하실 때 이부분 참고하세요!ㅎㅎ
너무 어려우시면, 아샬님의 피드백 강의를 보고, 힌트를 얻어 한번 구현해보세요!ㅎㅎ
저는 좋은 코드를 보고 따라하는 것도 성장하는 방법 중 하나라고 생각합니다!

2022-10-16 01:12 UTC, daadaadaah commented on src/index.js
> +  const getOperator = (operator) => {
`getOperator`라는 함수명을 보면, operator return해주는 함수로 이해할 수 있을 것 같아요!
좀더 적절함 함수명으로 바꿔봅시당!ㅎㅎ

2022-10-16 07:31 UTC, sejineeee commented
[39e9120](https://github.com/CodeSoom/react-week1-assignment-2/pull/178/commits/39e91209e8b0ff274a5a37ff6bda0d192e4418e5) 과제풀이를 참고하여 수정하였습니다!

연산자 버튼을 `Object.keys()`를 이용했었는데, 이렇게 하니 `=`을 분리해야 되고, 따로 버튼을 구현해야 했습니다. 또한 if 조건문을 이용해서 `=`일 때, 다른 처리를 해주도록 구현해야 했습니다. 이러한 방향으로 구현해보려고 했으나, 제대로 동작이 되지 않아, 과제 풀이를 통해서 수정하는 방향으로 결정하여 구현했습니다.

이번주 리뷰 감사합니다!! 🤩

2022-10-16 09:34 UTC, sejineeee commented
[1e65ea0](https://github.com/CodeSoom/react-week1-assignment-2/pull/178/commits/1e65ea00c0c29fbd7ad566135f7bc2cae61777da) 계산 과정에서 숫자 0을 선택했을 경우, 화면에 표시되지 않는 부분을 수정하여 다시 올렸습니다!! 감사합니다!! 🥺

2022-10-17 09:49 UTC, merged