과제2
CodeSoom/week1-assignment-2 pull request #180
Opened 2022-10-13 09:33 UTC by Sunset-Kim

# 작업내용
- render 함수에 state를 전달하여 문제를 해결했습니다.
- state는 immutable 하게 항상 생성하여 삽입했습니다.

# 궁금한 내용
- [ ] : 조건 분기가 많을 경우에는 어떻게 처리해야 할까요?

2022-10-14 06:38 UTC, daadaadaah requested changes
전반적으로 로직인 좀 복잡해요😅 과제1도 끝내셨으니, 코드를 좀더 간단하게 표현할 있는 방법에 대해 한번 고민해보시는거 좋을 것 같아요!ㅎㅎ

> 조건 분기가 많을 경우에는 어떻게 처리해야 할까요?

- 상황마다 다를 것 같은데, 저는 객체를 활용하기도 해요!

2022-10-14 06:38 UTC, daadaadaah commented on src/index.js
> +}
switch문은 대표적으로 코드 가독성이 좋지 않은 표현이예요! switch 문을 사용하지 않고 코드를 표현할 수 있는 방법은 없을까요? 가독성이 좋지 않은 코드에 대해 더 공부해보고 싶으시면, 클린코드 같은 도서 한번 읽어보시는거 추천드려요!ㅎㅎ

2022-10-14 06:38 UTC, daadaadaah commented on src/index.js
> +};
`display`, `prev` 보다 좀더 의도가 드러나는 변수명은 없을까요?🤔

2022-10-14 06:38 UTC, daadaadaah commented on src/index.js
> +          <button type="button" onClick={() => handleClick(str)}>{str}</button>
`str` 보다 좀더 의도가 드러나는 변수명은 없을까요?🤔

2022-10-14 06:38 UTC, daadaadaah commented on src/index.js
> +  const handleClick = (value) => {
`value` 보다 좀더 의도가 드러나는 변수명은 없을까요?🤔

2022-10-14 11:39 UTC, Sunset-Kim commented on src/index.js
> +}
넵 객체또는 생성자로 표현할 수 있는 방법에 대해서 한번 생각해보겠습니다! 오늘 조금 늦게 커밋할 것 같아요

2022-10-14 13:21 UTC, Sunset-Kim commented on src/index.js
> +          <button type="button" onClick={() => handleClick(str)}>{str}</button>
operator 가 넘어와서 operator로 변경했습니다

2022-10-14 13:22 UTC, Sunset-Kim commented on src/index.js
> +};
render 를 하기위한 state를 class로 생성하게 수정했고,
각각의 key 명을
displayNumber, result, operator, prevInput 으로 수정했습니다

2022-10-14 13:23 UTC, Sunset-Kim commented on src/index.js
> +  const handleClick = (value) => {
서로다른 value가 들어와서 value라고 명명했지만,
input이 적절한 것 같아서 input으로 변경했습니다.

2022-10-15 03:26 UTC, daadaadaah requested changes
잘하셨어요!ㅎㅎ아샬님 피드백 강의를 보며, 나의 코드와 어떤 점이 다른지 한번 비교해보세요!ㅎㅎ

2022-10-15 03:26 UTC, daadaadaah commented on src/index.js
> +}
객체를 사용했을 때와 비교하여 `class`를 사용하게 되면 어떤 장점이 있나요?ㅎㅎ

2022-10-15 03:26 UTC, daadaadaah commented on src/index.js
> +  };
함수가 1가지 역할 할 수 있도록 2개의 함수로 분리해보시는거 어떠신가요?ㅎㅎ

2022-10-15 06:20 UTC, Sunset-Kim commented on src/index.js
> +}
1. 객체를 사용했을때 보다 class의 static method 처리하는 것이 더 좋다고 생각합니다.
자바스크립트에서 객체는 함수를 보관하기에는 override에 취약해서 조금더 안전한 방법인 것 같습니다. 
도중에 접근해서 값을 바꾸는 등의 일에 취약하다고 했습니다. 그래서 커플러객체를 통해 스태틱한 메소드를 연결해야겠다는 생각을 했습니다! 또 나중에 calculate를 확장해서 더 많은 기능을 가진 calculate를 만들기도 쉽겠다고 생각했습니다.

2. 제가 만든 render 는 state를 항상 만들어서 넘겨줘야하는데  넘겨줘야하는 state를 매번 하드코딩하는 것보다 넘겨줘야하는 state의 틀이 있는 편이 났다고 생각했습니다

2022-10-15 06:23 UTC, Sunset-Kim commented on src/index.js
> +  };
click을 한다는 개념에서는 같은 함수에서 처리하는 게 맞다고 생각했는데, 
reviewer님 말씀대로 불필요한 함수가 될 수 있다고 생각이드네요! 
수정하겠습니다!

2022-10-16 01:49 UTC, daadaadaah requested changes

2022-10-16 01:49 UTC, daadaadaah commented on src/index.js
> +}
개인적인 의견으로는 코드가 더 길어져서 읽기가 불편한 단점이 있는데, 이 단점을 보완할정도의 장점은 아닌 것처럼 느껴집니다ㅠㅠ
확장성 측면에서도, 계산기의 동작이 덧셈, 뺄셈, 나눗셈, 곱셈 이외의 동작이 있지 않아아서, 객체로 관리하는게 더 낫지 않아 라는 생각이 듭니다!ㅎㅎ그리고, 아마 코드숨 교육기간 동안에 아샬님은 `class` 없이도 충분히 다른 기능들을 구현 가능하다는 걸 보여주실거예요ㅎㅎ아는게 많으셔서 다양한 생각을 하시는 것 같은데, 코드숨 교육기간 동안에는 좀더 간단히 작성하는 방법에 대해 훈련해보시는 거 추천드려요!ㅎㅎ

2022-10-17 09:49 UTC, merged