1주차 과제 - 간단 계산기 만들기
CodeSoom/week1-assignment-2 pull request #181
Opened 2022-12-07 11:21 UTC by KwangMin-Moon

안녕하세요 트레이너님

아직 과제 진행 중입니다~!  
변경 되는 상태값을  외부 변수 선언 없이 어떤 식으로 저장해야 할 지 고민하다고 우선 객체로 저장해서 시도해보고 있습니다.

2022-12-08 06:31 UTC, daadaadaah requested changes
좋습니다! 계속 진행해주세요~

2022-12-08 06:31 UTC, daadaadaah commented on src/index.js
> +function render(state) {
자바스크립트의 경우, 함수 매개변수 기본값 설정할 수 있습니다. 한번 활용해보시는 건 어떠신가요?
참고
- https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Functions/Default_parameters

2022-12-08 06:31 UTC, daadaadaah commented on src/index.js
> +function render(state) {
자바스크립트의 경우, 함수 매개변수 기본값 설정할 수 있습니다. 한번 활용해보시는 건 어떠신가요?
참고
- https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Functions/Default_parameters

2022-12-08 13:00 UTC, KwangMin-Moon commented
아직 과제 미완성입니다ㅜㅜ
계산기 로직이 계속 꼬이네요ㅜㅜ 바로 앞만 생각하고 짜니까 뒤로 갈 수록 state 관리가 안되고 있습니다

`if (state.operator === '+') {
        state.operator = operator;
        state.newNum = state.lastNum + state.newNum;
        render(state);
        state.lastNum = state.newNum;
        state.newNum = 0;
      }`
위 코드에서 state.operator를 바로 연산자로 사용할 방법이 없을까요?
state.newNum = state.lastNum + state.newNum; 여기에 연산자 + 대신 바로 넣어주고 싶은데 문자열이라 계속 NaN가 나오네요ㅠㅠ

2022-12-09 09:32 UTC, daadaadaah requested changes
> if (state.operator === '+') { state.operator = operator; state.newNum = state.lastNum + state.newNum; render(state); state.lastNum = state.newNum; state.newNum = 0; }
위 코드에서 state.operator를 바로 연산자로 사용할 방법이 없을까요?
state.newNum = state.lastNum + state.newNum; 여기에 연산자 + 대신 바로 넣어주고 싶은데 문자열이라 계속 NaN가 나오네요ㅠㅠ

- 그렇게 하고 싶은신 의도가 혹시 if문을 제거하고 싶으셔서 그런건가요?

2022-12-09 09:32 UTC, daadaadaah commented on src/index.js
> +  };
객체를 활용해서 복잡한 if else 문을 없애볼까요?

2022-12-26 12:01 UTC, merged