1주차 과제 - 간단 계산기 만들기
CodeSoom/week1-assignment-2 pull request #183
Opened 2022-12-08 12:18 UTC by naji0001

안녕하세요 강사님

어떻게 과제를 마무리한 것 같습니다.
하지만 else if문이 남발하고 매개변수가 왔다갔다 하니 가독성이 별로 좋지 않은거 같습니다.
개선할부분 알려주시면 감사하겠습니다!

2022-12-09 09:29 UTC, daadaadaah requested changes

2022-12-09 09:29 UTC, daadaadaah commented on src/index.js
> +function render(acc, cur = 0, operator = '') {
혹시, [RORO 패턴](https://www.freecodecamp.org/news/elegant-patterns-in-modern-javascript-roro-be01e7669cbd/)에 대해 들어보셨나요? 한번 공부해보시고 적용시켜보세요!

2022-12-09 09:29 UTC, daadaadaah commented on src/index.js
> +  }
- 아래 코멘트 외에 코드의 가독성을 높혀주는 방법에 대해 공부해보고 싶으시면, [클린 코드](http://www.yes24.com/Product/Goods/11681152) 한번 읽어보시는 거 추천 드려요!
1. 스스로 if else 문이 가독성이 별로 좋지 않다고 인지하신 점 너무 좋습니다!
객체를 활용해서 한번 코드를 개선시켜볼까요?ㅎㅎ
2. `oper`, `acc` 등 약어 보다 좀더 의도가 드러나는 표현은 없을까요?

2022-12-09 15:32 UTC, naji0001 commented on src/index.js
> +  }
트레이너님께서 말씀하신대로 객체를 활용해서 개선시켜보았습니다.
코드가 훨씬 나아졌지만 아직 많이 부족한것 같습니다.
주말동안 미루고 미루던 클린코드 봐야겠습니다.
감사합니다!

2022-12-10 04:49 UTC, daadaadaah requested changes
좋습니다! 코드가 전보다 훨씬 깔끔해졌네용!👍
클린코드도 좋고 저는 리팩터링 2판도 가독성 좋은 코드 작성하는데 도움이 되었던 것 같아요!ㅎㅎ

2022-12-10 04:49 UTC, daadaadaah commented on src/index.js
> +  function insertNumber(number) {
맥락 구분을 위해 한줄씩 띄어줍시다!

2022-12-10 04:49 UTC, daadaadaah commented on src/index.js
> +  function insertOperator(operator) {
맥락 구분을 위해 한줄씩 띄어줍시다!

2022-12-10 04:49 UTC, daadaadaah commented on src/index.js
> +      render({ currentValue: operators[currentOperator](accumulator, currentValue) });
`value`보다 좀더 의도가 드러나는 표현을 써보시는건 어떠신가요?

2022-12-10 04:49 UTC, daadaadaah commented on src/index.js
> +          <button type="button" onClick={() => insertNumber(number)}>
`insert`라고 하니까 뭔가 DB 접속하는 느낌이 나요ㅎㅎ다른 표현은 없을까요?ㅎㅎ

2022-12-10 11:59 UTC, naji0001 commented on src/index.js
> +      render({ currentValue: operators[currentOperator](accumulator, currentValue) });
`currentValue`  ->  `currentNumber` 로 변경하였습니다.

2022-12-10 12:00 UTC, naji0001 commented on src/index.js
> +          <button type="button" onClick={() => insertNumber(number)}>
`insertNumber`  ->  `handleClickNumber`, `insertOperator`  ->  `handleClickOperator`
로 변경하였습니다.

2022-12-10 12:02 UTC, naji0001 commented on src/index.js
> +  function insertOperator(operator) {
new line 추가 하였습니다

2022-12-11 11:29 UTC, daadaadaah approved these changes
과제하시느라 고생 많으셨습니다!👏👏
피드백 강의를 보면서 아샬님은 어떻게 문제를 해결하셨는지 잘 관찰해보세요!
회고 하시는거 잊지마시구요!💪

2022-12-26 12:01 UTC, merged