[과제2] 스텝 바이 스텝으로 올리는 중입니다.
CodeSoom/week1-assignment-2 pull request #29
Opened 2020-09-15 14:08 UTC by juunini

일단 뷰만 만들었습니다.
기능이 하나씩 될 때 마다 커밋하겠습니다.
(아직 작동은 안되서 테스트는 실패합니다.)

2020-09-16 08:47 UTC, juunini commented
일단 기능을 동작하게 해서 인수테스트를 완료하는 과정까지는 성공했습니다.
리펙토링 하기 전에 트레이너님의 리뷰를 받고싶습니다 :)

2020-09-16 15:45 UTC, hannut91 requested changes

2020-09-16 15:45 UTC, hannut91 commented on src/modules.js
> +}
`switch` 문이나 `if`문 없이 이 문제를 해결하려면 어떻게 해야할까요?

2020-09-16 15:45 UTC, hannut91 commented on src/index.js
> +function render(displayNumber = 0, waitingNumber, waitingOperator, lastInput) {
매개변수가 점점 많아져서 복잡해지는 것 같습니다. 매개변수가 많아질 때 매개변수를 의미로 묶을 수 있는 객체로 분리할 수 있을까? 고민을 해보시면 좋을 것 같습니다. 

See also
  - https://github.com/hannut91/refactoring-practice/tree/master/6.8-introduce-parameter-object
  - https://refactoring.com/catalog/introduceParameterObject.html

2020-09-16 15:45 UTC, hannut91 commented on src/index.js
> +      const afterDisplayNumber = parseFloat(displayNumber.toString() + number, 10);
displayNumber를 문자열로 변경시켜 뒤에 숫자를 붙이기 위해서 형변환을 하신 것 같아요. 형 변환없이 이 문제를 해결하려면 어떻게 해야할까요?

1이 있는 상황에서 5를 누르면
15가 되야겠죠.
사실 15는 10 + 5죠.

2020-09-16 15:45 UTC, hannut91 commented on src/index.js
> +  }
```js
function handleClickNumber(number) {
  const displayNumber = typeof lastInput === 'number'
    ? parseFloat(displayNumber.toString() + number, 10)
    : number;

  render(displayNumber, waitingNumber, waitingOperator, number);
}
```

이런식으로 하면 lastInput에 따라서 displayNumber가 뭐가 될지 결정한다는 것을 더 드러낼 수 있을거에요. 
그리고 

```js
render(afterDisplayNumber, waitingNumber, waitingOperator, number);
render(number, waitingNumber, waitingOperator, number);
```

이렇게 중복되는 모습도 제거할 수 있을거에요

2020-09-17 03:14 UTC, juunini commented on src/modules.js
> +}
eval 이라는 함수를 발견했으나, injection attack에 취약하다고 하여서 객체 형식으로 변경했습니다.

```javascript
export const Calculate = {
  '+': (number1, number2) => number1 + number2,
  '-': (number1, number2) => number1 - number2,
  '*': (number1, number2) => number1 * number2,
  '/': (number1, number2) => number1 / number2,
};
```

2020-09-17 03:17 UTC, juunini commented on src/index.js
> +function render(displayNumber = 0, waitingNumber, waitingOperator, lastInput) {
처음에는 `{ [displayNumber, waitingOperator, waitingNumber], lastInput }` 이런 내용의 객체를 받도록 변경하려고 계획습니다.
하지만, 앞에 `[displayNumber, waitingOperator, waitingNumber]` 이 세가지를 갖는 스택을 기반으로 리펙토링을 진행하니
`lastInput` 이 결국 필요가 없어졌고, 최종적으로는 아래처럼 리펙토링이 되었습니다.

```javascript
function render(store = new Stack([0])) {
```

2020-09-17 03:18 UTC, juunini commented on src/index.js
> +      const afterDisplayNumber = parseFloat(displayNumber.toString() + number, 10);
단순한 원리인데 모르고 있었네요 ㅠㅠ

2020-09-17 03:22 UTC, juunini commented on src/index.js
> +  }
변수에 값을 할당할 때 if-else를 안쓰고 삼항 조건 연산자를 사용하니 변수가 아니라 상수를 사용할 수 있구나 하는 부분을 깨달았습니다.
덤으로 해당 if-else 라는 의도를 굉장히 간단한 방식으로 표현이 가능하다는것두요. 감사합니다!

2020-09-17 15:19 UTC, hannut91 requested changes
Stack을 이용해서 문제를 해결해주셨네요. 스택 내부 구현을 보면 pop하는 순간 변수의 값 자체를 변경하고 있네요. 과제1에서 배웠던 것을 상기해보면 좋을 것 같아요

2020-09-17 15:19 UTC, hannut91 commented on src/modules.js
> +};
간단하게 x, y로 해도 좋을 것 같아요

2020-09-18 06:01 UTC, juunini commented on src/modules.js
> +};
수학시간에 쓰던 x, y를 생각을 못했군요 ㅎㅎ;
이렇게 고치는게 좀 더 직관적이고 좋아보여서 수정하였습니다. 감사합니다!

2020-09-18 06:04 UTC, juunini commented
트레이너님 죄송합니다만 스택 내부 구현에서 pop하는 순간 변수의 값 자체를 변경하고 있다는 의미를 이해하지 못했습니다 ㅠㅠ
어떤 부분인지 조금만 더 자세히 알려주실 수 있으실까요? 한번에 못알아들어서 죄송합니다 ㅠㅠ

2020-09-18 06:06 UTC, hannut91 commented
`pop`메서드는 해당 배열을 직접 고치는 메서드라서 변수를 직접변경시키고 있어요. 이는 우리가 과제1에서 했던 let을 쓰는 것과 같은 일을 합니다.

2020-09-18 06:09 UTC, juunini commented
pop을 하면 배열의 크기가 달라진다 라는 의미이신가요?

2020-09-18 06:14 UTC, juunini commented
아... 그렇다면 push도 같은 맥락이겠군요 ㅠㅠ

2020-09-18 16:43 UTC, juunini commented
pop, push를 제거하고 `render` 할 때 새로 만든 state를 할당하는 형식으로 변경해보았습니다.
스택인듯 스택아닌 스택같은 느낌이라 뭔가 잘못된듯한 느낌이 드네요 ㅠㅠ

결국 객체 형식으로 써도 똑같이 사용은 가능할 것 같습니다.
(확장성으로 보자면 객체로 갈아타는게 맞을 것 같기도 합니다...)

2020-09-19 04:02 UTC, ahastudio commented
예전 코드와 지금 코드를 비교해 보면서 어느 쪽이 더 단순하게 의도를 전달하고 있는지 장단점을 파악해 보면 좋을 것 같습니다.

https://github.com/CodeSoom/week1-assignment-2/pull/29/files/1e6beda280dc0843a6595163f66cc4adef1fb11e

2020-09-19 04:52 UTC, juunini commented
우문현답이군요 ㅠㅠ 감사합니다.
의도를 더 심플하게 잘 전달할 수 있는 방향으로 다시 생각해보겠습니다.

2020-09-19 14:04 UTC, hannut91 requested changes

2020-09-20 01:32 UTC, juunini commented on src/index.js
> +    : displayNumber;
아.. 이런 표현식이 있다는걸 몰랐군요 ㅠㅠ
덕분에 'null 병합 연산자' 라는걸 배웠습니다. 감사합니다!

2020-09-20 01:36 UTC, juunini commented on src/index.js
> +      : (displayNumber * 10) + number;
별 생각 없이 다음에 보여줄 값이라 new라고 썼는데, `new` 라는 단어가 가지는 상징성을 생각해보니 올바르지 않은 표현이었던 것 같습니다 ㅠㅠ
`new` -> `next` 로 변경했습니다.

2020-09-20 01:48 UTC, juunini commented on src/index.js
> +    });
아, 저렇게 표현이 가능했군요 ㅠㅠ
go랑 typescript에만 익숙하다보니 type 으로 미리 설정해두고 값을 받는게 아니라면 저렇게 할 생각을 못해봤던 것 같습니다. 감사합니다

2020-09-20 01:59 UTC, juunini commented on src/index.js
> +    : displayNumber;
사용해봤는데, babel에서 계속 에러가 나는 바람에 `@babel/plugin-proposal-nullish-coalescing-operator` 를 추가할 수 밖에 없었습니다 ㅠㅠ

2020-09-20 13:20 UTC, hannut91 approved these changes
고생하셨어요 ㅎㅎ 굉장히 많은 변화가 있었네요. 앞으로 올라올 과제풀이 영상을 통해서 다시 한 번 복습해보시면 좋을 것 같아요. 풀이과정을 어떻게 전개하는지 눈여겨 보면 좋을 것 같아요.

2020-09-20 13:20 UTC, hannut91 commented
이번 주 과제를 통해서 무엇을 배우셨나요?

2020-09-20 14:29 UTC, juunini commented
# 깨달은 것
1. 의도를 가장 알기 쉽고 간단하게 전달할 수 있는 코드를 짜야 한다.
2. "`if-else`나 `switch` 를 안쓰면 어떻게 이걸 표현해?" 라고 생각했던 것이 가능했다. 오히려 더 안전하고 세련됐다.
3. 변수명은 좀 더 생각을 해야한다. 단어가 가지는 상징성도 고려해야 한다.
4. 모르고 있었지만, 모던 자바스크립트의 세련된 기법들이 많다는 사실을 알았다.
5. 커밋은 잘게잘게... 목표를 작게 나눠서 하나씩 개발해야 크게 틀어지는 일이 없다는걸 깨달았다.
6. 테스트는 정말 중요하다. 아마 테스트를 하는 부분이 없었다면 개발 시간이 10배는 길어졌을 것 같다.

---

이번 주 과제를 통해서는 이렇게 배우고 알게된 것 같습니다!

2020-09-21 15:16 UTC, merged