[Week1][Davidyang2149]Update make Calculator (진행 중)
CodeSoom/week1-assignment-2 pull request #30
Opened 2020-09-15 15:25 UTC by DavidYang2149

# 1강 JSX - 1주차 과제 2
## 요구사항
- [ ] ESLint를 돌린 결과 아무런 문제가 없어야 합니다.
- [ ] 모든 인수 테스트를 통과시켜야 합니다.

## 구현할 기능들
- [x] 숫자를 누르면 누른 숫자가 출력되어야 합니다.
- [ ] 숫자를 연속해서 누르면 숫자가 더해져서 출력되어야 합니다.
- [ ] 숫자와 연산자를 입력한 후 =를 클릭하면 계산 결과가 출력되어야 합니다.
- [ ] 연속해서 숫자와 연산자를 입력하면 중간에 계산 결과가 출력되어야 합니다.

## 작업 내용
- 커밋1 : 간단 계산기의 view 구현 & 각 버튼에 사용할 function 제작(기능은 미구현).

## 질의
- (없음 - 작업 진행 중)

2020-09-16 14:01 UTC, DavidYang2149 commented
진행 상황
1. 각 숫자를 클릭시 숫자가 더해지게 됨(완료).
2. =을 사용할 시 결과값은 계산되지만 결과를 정상적으로 표시하지 못하게 됨.
3. Git commit 메시지를 수정하는 과정에서 conflict 발생.

점점 실타래가 꼬이는데 어디서부터 바라보고 수정을 해야할지 감이 잡히지 않습니다. 😭
도움을 요청드립니다!

2020-09-16 16:07 UTC, hannut91 requested changes
깃 커밋같은 경우 어떻게 하다가 꼬여서 어떤 문제가 발생했는지 DM으로 알려주시면 도움드리겠습니다!

2020-09-16 16:07 UTC, hannut91 commented on src/index.js
> +    return render(parseFloat(selectNum.toString() + originNum.toString()), tempNum, selectOperator);
숫자를 이어 붙이기 위해서 형변환 한 다음에 다시 형변환을 하신 것 같아요. 형변환없이 문제를 해결할 수 있을까요?

예를들어서 1이 있는데 5를 누르면 15가 되죠. 사실 15는 10 + 5입니다

2020-09-16 16:07 UTC, hannut91 commented on src/index.js
> +    }
eqaul연산자는 다른 일을 하는데 같은 함수에서 처리를 하려고 하니 `if`문이 많이 생긴 것 같아요. equal 연산자는 다른 함수로 처리해주는건 어떨까요?

2020-09-17 11:05 UTC, DavidYang2149 commented on src/index.js
> +  const calculator = (selectOperator, firstNumber, secondNumber) => {
그렇네요!
사실 연산자(operator) 자체로 변수명을 짓는 것이 옳다고 생각됩니다.
그리고 calculator 함수는 독립성을 가지고 있어서 굳이 render 함수 안에 있을 필요가 없다고 판단하여 밖으로 꺼내었습니다.

2020-09-17 11:05 UTC, DavidYang2149 commented on src/index.js
> +    return render(parseFloat(selectNum.toString() + originNum.toString()), tempNum, selectOperator);
생각지도 못했네요! 좋은 방법 감사합니다.

2020-09-17 11:35 UTC, DavidYang2149 commented on src/index.js
> +  };
`if`나 `switch`문(조건문)이 없이 처리를 하기 위해 고민하다가 `object`에 property를 부여하는 방식으로 접근을 해보았습니다.
이렇게 `object`로 처리하니 내용이 더 간결하고 명시적으로 보이네요.
이렇게 하는 것이 맞을까요?

2020-09-17 14:50 UTC, DavidYang2149 commented on src/index.js
> +    }
말씀해주신 대로 eqaul 연산자를 별도의 함수로 분리하려 했으나 다음과 같은 이유로 작업을 보류했습니다.

1. 당시에는 `handleNumberClick` 함수와 `handleCalculationClick` 함수에 필요했으나 최종 `handleCalculationClick`에서만 사용하는 것으로 수정.
2. `handleCalculationClick` 함수의 `if`문을 4개에서 3개로 축소함.

최종 완성된 코드에 대한 피드백을 주시면 다시 반영해보겠습니다.

감사합니다. 😀

2020-09-17 14:55 UTC, DavidYang2149 commented
## 기능 구현 완료 후 회고
1. 함수의 복잡도 관리 : 각 함수의 최소한 필요한 기능이 무엇인지 생각해보고 순서대로 구현하였습니다.
2. 파라미터 관리 : 함수의 파라미터가 증가하면서 코드를 읽는 속도와 효율성이 떨어진다고 생각되었습니다.
                           그래서 파라미터를 객체(와 프로퍼티들)로 변경하고 싶다는 생각이 들었는데 이 방법이 괜찮은 것인지 모르겠습니다.
3. 완료 : 기능 구현을 완료한 뒤 무엇을 더 개선할 수 있는지 고민해보아야겠습니다.

2020-09-17 15:19 UTC, hannut91 commented on src/index.js
> +  };
네 좋습니다 ㅎㅎ

2020-09-17 15:25 UTC, hannut91 requested changes

2020-09-17 15:25 UTC, hannut91 commented on src/index.js
> +};
`firstNumber` 대신에 x, y로 표현해도 괜찮을 것 같아요

2020-09-17 15:25 UTC, hannut91 commented on src/index.js
> +  const Calculation = {
변수의 이름은 camelCase로 작성하는게 좋을 것 같아요

2020-09-17 15:25 UTC, hannut91 commented on src/index.js
> +  };
선택한 연산자를 나타내기 위해서 `selectOperator`라는 변수이름으로 사용하신 것 같아요. handleNumberClick이라는 함수 입장에서 보면 선택된 연산자인지는 사실 중요하지 않고 주어진 연산자를 처리를 하기만 하면됩니다. `선택된`이라는 컨텍스트를 가질 필요가 없고 가지면 안됩니다. 

그리고 selectOperator는 연산자를 선택하는 함수처럼 보여요. 왜냐하면 명령문이기 때문이에요.

2020-09-17 15:25 UTC, hannut91 commented on src/index.js
> +  const handleNumberClick = (selectOperator, selectNum, originNum, tempNum) => {
render함수 안에서는 `operator, count, tempCount, viewCount`들은 안에 캡쳐되어서 `handleNumberClick`에서 사용하더라도 순수한 함수이기 떄문에 많은 매개변수를 넘겨줘서 해결하지 않아도 괜찮습니다. 계속 너무 많은 매개변수가 있다보니 복잡해보입니다.

2020-09-17 15:25 UTC, hannut91 commented on src/index.js
> +    if (originOperator !== '') {
operator가 비어있지 않으면 해당 함수를 실행하는 것 같아요. 조건문안에 부정문이 들어가면 읽기가 굉장히 어려워집니다. 특별한 상황이 아니면 긍정문을 사용하는게 좋습니다.

2020-09-18 08:45 UTC, DavidYang2149 commented on src/index.js
> +    if (originOperator !== '') {
조건문을 작성할 때는 부정문보다는 긍정문으로.
꼭 기억하겠습니다!

2020-09-18 08:46 UTC, DavidYang2149 commented on src/index.js
> +};
수정해보니 코드가 더욱 간결하게 보입니다.  👍

2020-09-18 09:08 UTC, DavidYang2149 commented on src/index.js
> +  };
함수는 함수 자체의 독립적인 입장이다는 전제를 가지고 변수명을 봐야겠네요.
감사합니다~!

2020-09-18 11:21 UTC, DavidYang2149 commented on src/index.js
> +  const handleNumberClick = (selectOperator, selectNum, originNum, tempNum) => {
네. 저도 그 부분이 찜찜했습니다. 
해당 내용을 반영하였습니다!

2020-09-18 11:33 UTC, DavidYang2149 commented
## 1차 리팩토링 완료 후 회고
1. 매개변수, 변수 이름 재정의 :  변수 이름은 단순하고 간결(쉽게)하게 합니다. 함수에서 매개변수를 설정할 때는 함수의 독립적인 기능을 고려합니다.
2. 조건문의 긍정문과 부정문 :  조건문을 작성할 때는 부정문보다는 긍정문으로 작성합니다. 내용이 더 직관적입니다.

2020-09-18 14:03 UTC, hannut91 requested changes

2020-09-18 14:03 UTC, hannut91 commented on src/index.js
> +function render(operator = '', count = 0, tempCount = 0, viewCount = 0) {
함수의 매개변수가 너무 많아져서 너무 복잡해지는 것 같아요. 그리고 함수를 사용할 때도 넘겨주는 값이 어떤 값인지 이름이 드러나지 않는 것 같아요. 코틀린은 named parameter라고 해서

```kotlin
something(name = "yusenok");
```

이런식으로 사용할 수 있는데 자바스크립트는 지원하지 않죠. 대신에 객체를 넘기는 방식을 많이 사용합니다.

```js
something({name: "yunseok"});
```

그러면 내가 넘기는 값이 무엇인지 이름을 명확하게 표현할 수 있고, 내가 optional하게 값을 넘기고 싶을 때도 더 간단하게 사용할 수 있습니다. 

See also
  - https://github.com/hannut91/refactoring-practice/tree/master/6.8-introduce-parameter-object
  - https://refactoring.com/catalog/introduceParameterObject.html

2020-09-18 14:03 UTC, hannut91 commented on src/index.js
> +    const resultNum = calculator(operator, tempCount, count);
`number`를 줄여서 `num`으로 사용하신 것 같아요. 변수는 특별한 상황이 아니면 줄여쓰지않는게 좋습니다.

2020-09-18 14:03 UTC, hannut91 commented on src/index.js
> +      render('', 0, 0, calculator(operator, tempCount, count));
`calculator`는 계산기를 의미하는 것 같아요. 계산한다는 것을 더 드러내기 위해 `calculate`는 어떨까요?

2020-09-19 04:05 UTC, ahastudio commented
temp, view count 등을 명확히 하려면 사전을 찾아보셔도 좋습니다. Kent Beck은 개발할 때 책상 위에 영영사전을 둔다고 해요.

2020-09-19 10:41 UTC, DavidYang2149 commented on src/index.js
> +    const resultNum = calculator(operator, tempCount, count);
처음에 코드를 작성할 때 길이가 길어져서 num로 줄여서 작성했습니다.
그 이후에 수정하는 것을 놓쳤네요.
해당 내용 수정하였습니다!

2020-09-19 10:42 UTC, DavidYang2149 commented on src/index.js
> +      render('', 0, 0, calculator(operator, tempCount, count));
이름짓기를 하면서 변수는 명사형으로 접근하고, 함수는 동사형으로 접근하는 케이스가 많아지는 것 같습니다.
피드백 감사합니다!

2020-09-19 10:43 UTC, DavidYang2149 commented on src/index.js
> +  };
로직이 변경되면서 기존에 만든 기능이 불필요해졌네요.
앞으로 로직이 변경되면 처음부터 다시 복기해보는 습관을 가져보겠습니다.

2020-09-19 10:45 UTC, DavidYang2149 commented on src/index.js
> +function render(operator = '', count = 0, tempCount = 0, viewCount = 0) {
역시 number가 괜찮다고 생각되어 수정했습니다.
아샬님께서 주신 피드백을 참고로 정말 오랜만에 영어사전을 꺼내 보았습니다.
number와 비슷한 numeral.
또 계산기 테마에서 사용할 수 있겠다고 생각되는 numbering.
을 얻을 수 있었습니다!

2020-09-19 12:10 UTC, DavidYang2149 commented on src/index.js
> +function render(operator = '', count = 0, tempCount = 0, viewCount = 0) {
이번 주에 작업한 리팩토링 중에 가장 많은 시간이 걸렸습니다.
그만큼 많은 생각이 들었고 배웠습니다.

1. 함수의 매개변수를 넘길 때 어떤 것이 존재하는지, 그리고 어떤 값이 변경되는지 더 명확하게 알 수 있다.
```js
function render(state) {
  const {
    operator,
    number,
    memoryNumber,
    displayNumber,
  } = state;
...
  const handleNumberClick = (numeral) => {
    const addNumber = numeral + (number * 10);
    render({
      ...state,
      number: addNumber,
      displayNumber: addNumber,
    });
  };
...
}
```

내용을 수정한 후 느껴진 장점은 다음과 같았습니다.
- 조건 : render 함수의 매개변수를 object 타입으로 설정 후, `handleNumberClick` 함수 내부에서 `render` 함수를 호출할 시.
- 장점1 : 기존 유지된 값은 `...state`로 보존하고 나머지 변경되는 값을 구분.
- 장점2 : 변경된 값이 어떤 것이 변경되었는지를 명시적으로 알 수 있다(displayNumber: addNumber - **보이는 숫자**는 **더해진 숫자**입니다).

2. initialize의 방법
여기서 많이 헷갈렸는데 결국 찾아낸 방법은 마지막 라인의 `render`함수에 초깃값을 대입하는 것이었습니다.
이 방법이 옳은 것인지는 모르겠습니다.


여기까지 작업을 했는데 더 깊이 들어가면 class형으로 제작하여 모듈을 분리해 접근하는 방법도 가능하지 않을까하는 생각이 들었습니다.
그러나 복잡하게 만들기보다는 우선 단순하게 접근하는 것이 더 효율적이고 보기 쉽겠다는 생각이 들었습니다.

2020-09-19 12:27 UTC, DavidYang2149 commented
## 2차 리팩토링 완료 후 회고
### 1. 이름 재정의 
이름 재정의에 대한 고민이 계속 이어졌습니다. 
변수는 단순하고 명확한 것이 좋다고 생각되었습니다.
함수는 동사형(행동이나 행위)으로 접근하는 케이스가 많은 것 같습니다.

### 2. 로직 변경에 따른 재검토
함수의 로직을 리팩토링하면서 가지고 있던 조건문이 불필요하진 경우가 있었습니다. 
리팩토링 후에는 다시 처음부터 올라가서 기존 로직 중 추가로 필요하거나 없어도 되는 것이 있는지 확인해야겠습니다.

### 3. 함수의 매개변수 변경
매개변수가 계속 늘어나면서 고민이 되었습니다.
매개변수가 얼마나 늘어나면 객체, 혹은 배열로 변경해야 할까(개인적으로는  3개 이상으로 생각됩니다)? 
매개변수를 객체로 변경하면서 얻은 이득은 무엇일까?
- 객체 안에 어떤 프로퍼티들이 보관되어 있는지 구분이 가능하다(정리정돈).
- 입력된 값의 이름을 통해 **무엇이** **어떻게** 적용되었는지 확인할 수 있다.

같은 코드를 반복해서 파볼수록 깊이가 느껴집니다 😍.

2020-09-19 14:17 UTC, hannut91 approved these changes
변수 이름에 대해서 고민하신 흔적이 많이 보여서 좋네요 ㅎㅎ 앞으로도 좋은 코드의 작성은 변수 이름부터 시작하시면 좋을 것 같아요. 처음 코드와 마지막 코드에서 어떤 변화가 일어났는지 다시 한 번 생각해보시면 좋을 것 같습니다. 그리고 과제풀이영상을 보면서 어떻게 문제를 해결해나가는지 중점으로 보면서 다시 한 번 복습해보면 좋겠습니다.

2020-09-19 14:17 UTC, hannut91 commented on src/index.js
> +    const addNumber = numeral + (number * 10);
`addNumber`가 코드를 이해하는데 도움이 되지 않는 것 같아요. 이미 우변이 의도를 충분히 설명하고 있는 것 같아요. Inline varaible리팩터링을 하면 좋을 것 같아요.

See also
  - https://github.com/hannut91/refactoring-practice/tree/master/6.4-inline-variable
  - https://refactoring.com/catalog/inlineVariable.html

2020-09-19 14:17 UTC, hannut91 commented
이번 주 과제를 하면서 무엇을 배우셨나요?

2020-09-20 03:28 UTC, DavidYang2149 commented on src/index.js
> +    const addNumber = numeral + (number * 10);
네 해당 케이스를 반영하였습니다~!

2020-09-20 04:11 UTC, DavidYang2149 commented
## 3차 리팩토링 완료 후 회고
### 1. 변수 인라인
같은 내용을 반복한다고 무조건 변수를 만들기보다, 코드가 의도를 충분히 드러내는지 고려하고 그에 따라 변수를 만들어야겠습니다.

### 2. 변수 위치 조정과 초기화
`handleCalculationClick` 함수를 리팩토링, 수정하였습니다.
변수 `resultNumber`는 `calculate` 함수의 결괏값을 담고 있습니다.
- `calculate` 함수의 중복 케이스를 발견하여 변수 `resultNumber`를 상단으로 이동하였습니다.
- 로직 변경에 따른 함수를 재검토한 결과, 변수 `resultNumber`가 undefined일 때 오류가 발생할 수 있다는 것을 알았습니다.
- 그래서 undefined일 경우 0으로 설정되게 수정하였습니다.

리팩토링을 반복하며 배운 것을 적용하니 즐겁습니다 😀.

2020-09-20 10:16 UTC, DavidYang2149 commented
# 1주차 과제 회고
## 한 것(Fact)
### 1. `let` 제거하기
#### 왜(why)?
불변성을 유지하기 위해(참조 투명성을 위해).
코드가 불변이면 초기 선언값을 믿고 작업할 수 있다.
### 2. ESLint 사용하기
#### 왜(why)?
코딩 컨벤션에 어긋나는 코드나 안티 패턴을 자동 검출해 준다.
좋은 코딩 스타일과 코드 품질을 만들 수 있다.
나중에 팀으로 작업할 때도 좋은 룰을 만들 수 있다는 생각이 들었다.
### 3. 인수 테스트 통과하기
#### 왜(why)?
인수 테스트를 통해서 기능의 신뢰를 할 수 있다(단, 테스트 케이스가 신뢰할 수 있다는 전제를 가진다).
작성된 테스트 케이스를 통해 코드가 통과되면 심리적인 안정감이 생겼다.

## 느낀 것(Feelings)
### 1. 코드리뷰
2년간 직장생활을 하면서 내가 작성한 코드에 자신감이 없었다.
코드 품질의 기준은 동작이 정상적으로 작동하는지 아닌지의 여부였다.
그동안 코드리뷰가 없어 내 코드의 품질이 어떤지 알지 못해 답답했다. 
이번 코드숨을 통해 내가 어떤 생각으로 코드를 작성했는지 또 어떤 습관을 지니고 있었는지 진단을 받을 수 있었다. 
그리고 내 상태를 알게 되면서 무엇을 고치고 보완해야 하는지 깨달았다. 
### 2. 리팩토링
처음 학원에서 프로그래밍에 대해 배울 때 리팩토링은 *기존 기능을 그대로 유지하면서 내부 구조를 개선*하는 것이라고 배웠다.
처음으로 코드리뷰를 통해 리팩토링해보았다.
사실 리팩토링이라고 불리는 것도 부끄러운 수준이지만 누구든 처음부터 만족하랴.
앞으로 남은 시간동안 열심히 해보자.
### 3. 인수 테스트
개발자 서적에 인수 테스트 혹은 TDD에 대한 개념을 보았는데, 글로 읽을 때는 '아 이런 개념이 있구나' 정도였다.
그런데 이번 인수 테스트를 해보고 코드가 모두 통과하는 것을 보면서 심리적인 안정감과 코드를 신뢰할 수 있게 되었다.
물론 테스트 케이스를 작성하는 방법을 배우고, 또 신뢰할 수 있는 테스트 케이스를 작성하는 것은 별개의 일이다.
앞으로 배울 인수 테스트가 궁금하고 기대된다.

## 배운 것(Findings)
### 1. inline variable 리팩토링 하기
#### 왜(why)?
변수명을 잘 짓는 것도 중요하지만, 우변의 식이 명확한 의미를 가진다면 그대로 대입하는 것이 더 좋은 방법일 수도 있다.
- 참조1 : https://refactoring.com/catalog/inlineVariable.html
- 참조2 : https://github.com/hannut91/refactoring-practice/tree/master/6.4-inline-variable
### 2. 화살표 함수를 사용할 때 중괄호를 잘 고려하기
#### 왜(why)?
화살표 함수를 한줄로 작성할 때는 중괄호를 생략할 수 있다.
하지만 작성한 코드가 반환하는 값이 없을 때는 중괄호를 포함시켜야 한다.
```js
const handleClick = (number) => {
  if (number === false) {
    // 하단의 render(0)은 반환값이 없다.
    render(0);
    return;
  }
  // 여기도 마찬가지로 render(number + 1)의 반환값이 없다.
  render(number + 1);
  return;
}
```
만약 `return render(number + 1);`로 작성했으면 `render(number + 1)`의 결과값을 리턴하는 것처럼 보인다.
그러나 실제 코드의 의도는 `render(number + 1)`의 작업을 진행한 후 종료하는 것이다.

2020-09-20 11:41 UTC, merged