간단한 사칙 연산 계산기 구현
CodeSoom/week1-assignment-2 pull request #34
Opened 2020-09-16 09:57 UTC by koremp

main 브랜치가 아닌 koremp 브랜치로 다시 PR 생성했습니다.

2020-09-16 16:11 UTC, hannut91 requested changes
eslint에서 에러가 나고 있는데 왜 이러한 룰들은 이런 스타일을 강요하는지 생각해보시면 좋을 것 같습니다!

2020-09-16 16:11 UTC, hannut91 commented on src/index.js
> +  switch (preOperator) {
switch나 if없이 이 문제를 해결할 수 있을까요?

2020-09-16 16:11 UTC, hannut91 commented on src/index.js
> +    preOperator = undefined;
여기서 변수를 재할당하고 있군요! 과제1에서 배운것을 다시 한 번 상기해보면 좋을 것 같아요

2020-09-16 16:11 UTC, hannut91 commented on src/index.js
> +          </button>
handler함수가 바깥에 있다보니 필요한 매개변수를 모두 전달해서 코드가 복잡해진 것 같아요. `handleClickNumber`가 `render`함수 안에 선언되어 있다면 매개변수가 캡쳐되어서 그대로 사용할 수 있고 그러면 `handleClickNumber`가 상당히 단순해질 수 있을거에요

2020-09-17 12:44 UTC, koremp commented on src/index.js
> +  switch (preOperator) {
operator를 그대로 사용할 수 있겠네요...

2020-09-17 15:27 UTC, hannut91 requested changes

2020-09-17 15:27 UTC, hannut91 commented on src/index.js
> +  currentNumber = eval(preNumber + " " + operator + " " + currentNumber);
`eval`은 사용하지 않는게 좋습니다.

See also
  - https://ko.javascript.info/eval

2020-09-17 15:27 UTC, hannut91 commented on src/index.js
> +  console.log(currentNumber);
사용되지 않는 console.log는 지우는게 좋을 것 같습니다

2020-09-17 15:44 UTC, koremp commented on src/index.js
> +  console.log(currentNumber);
알겠습니다

2020-09-18 14:26 UTC, hannut91 requested changes

2020-09-18 14:26 UTC, hannut91 commented on src/index.js
> +            onClick={() => handleClickCalc(currentNumber, preNumber, operator, preOperator)}>
`Calc`가 무엇인지 가늠하기 어려운 것 같아요. 변수의 이름은 특별한 상황이 아니면 줄여쓰지 않는게 좋습니다.

2020-09-18 14:26 UTC, hannut91 commented on src/index.js
> +  };
숫자를 클릭해서 넘어온 값이라서 `clickedNumber`라는 변수명을 사용하신 것 같아요. 변수를 클릭할 때는 `클릭했다`라는 컨텍스트가 있어서 자연스러운데, 이 `handleClickNumber`라는 함수의 입장에서는 이케 클릭해서 넘어온 값인지 그냥 실행해서 넘어온 값인지 관심사가 아닙니다. 

따라서 `number`라고만 해도 충분히 의미를 전달할 것 같습니다.

2020-09-19 04:19 UTC, ahastudio commented
JavaScript는 함수 안에 함수를 써줄 수 있습니다. Closure 때문에 앞으로도 적극 활용하게 될 거예요.

2020-09-19 14:23 UTC, hannut91 requested changes

2020-09-19 14:23 UTC, hannut91 commented on src/index.js
> +render(0, undefined, undefined, false);
`render`함수 안에서는 디스트럭처링을 통해 값을 받고 있는데 여기서는 하나씩 전달하고 있네요.

2020-09-19 14:23 UTC, hannut91 commented on src/index.js
> +  };
`clickedNumber`는 `clicked`는 이 매개변수에서는 관심사가 아닌 것 같습니다.

사용할 때는 

```js
const clickedNumber = 3;
handleClickNumber(clickedNumber);
```

이라고 사용할 수 있지만 `handleClickNumber`안에서는  `clicked`라는 이름이 없어도 상관없습니다.

2020-09-19 14:23 UTC, hannut91 commented on src/index.js
> +}
여러개의 값을 한 번에 처리할 수 있도록 accumulate를 만드신 것 같아요. 특정 계산기의 경우 한 번에 입력을 받고 한 번에 처리를 하는 계산기가 있는데, 이럴 경우 굉장히 유용할 것 같아요. 하지만 지금 저희가 만드는 계산기는 한 번에 한 번만 처리를 하므로 더 단순히 처리할 수 있을거에요

2020-09-20 13:24 UTC, hannut91 approved these changes
고생하셨습니다 ㅎㅎㅎ 처음 작성한 코드와 마지막 코드를 비교하면서 어떤 변화가 일어났는지 보시면 좋을 것 같아요.

과제풀이 영상을 통해서 다시 한 번 복습하면 좋을 것 같아요. 특히 아샬님은 어떻게 문제를 풀어나가는지 풀이과정을 눈여겨 보시면 좋을 것 같습니다.

2020-09-20 13:24 UTC, hannut91 commented on src/index.js
> +      });
스프렌드 문법을 사용하면 변경되는 값들만 표현할 수 있어서 더 의도를 드러내기 쉬울거에요.

```js
function render(state) {
  const { currentNumber, preNumber, preOperator, isOperated } = state;

  const handleClickNumber = (number) => {
    if (isOperated) {
      render({
        ...state,
        currentNumber: number,
        isOperated: false,
      });
    }
  }
}
```

See also
  - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

2020-09-20 13:24 UTC, hannut91 commented
이번 주 과제를 통해서 무엇을 배우셨나요?

2020-09-20 23:09 UTC, koremp commented on src/index.js
> +      });
대박적,,

2020-09-21 15:16 UTC, merged