week1-2 make calculator
CodeSoom/week1-assignment-2 pull request #35
Opened 2020-09-16 13:09 UTC by JamieShin0201

안녕하세요.

요구사항 기능들은 구현 하였는데 아직 no-use-before-define 에러를 해결하진 못하였습니다.

그리고 뭔가 저 자신도 이해하기 힘들정도로 복잡하게 로직을 만든 것 같습니다. 

계속해서 수정해보겠습니다! 감사합니다^^

2020-09-16 16:12 UTC, JamieShin0201 commented
안녕하세요!

1. rendor 함수안에 다른 함수들을 구현함으로써 no-use-before-define 에러를 해결하였습니다.

2. render 함수에 previousNumber, operator, afterNumber, resultNumber 4개의 매개변수를 받아 작업을 완료하였습니다.
2-1) previousNumber : 중간 연산결과를 저장, 연산자를 클릭했을때 afterNumber에서 값을 복사하는 변수 
2-2) operator : 연산자를 담기위한 변수
2-3) afterNumber : 사용자가 클릭하는 숫자를 담기 위한 변수
2-4) resultNumber : 사용자에게 결과를 보여주기 위한 변수

3. calculate, handleClickNumber, handleClickOperator 세개의 함수를 구현하였습니다.
3-1) calculate : 사칙연산 함수
3-2) handleClickNumber : 숫자를 입력 받아 처리하는 함수
3-3) handleClickOperator : 연산자를 입력받아 처리하는 함수

과제의 의도에 맞게 하고 있는지 궁금합니다. 

계속해서 리팩토링 해보겠습니다. 감사합니다^^

2020-09-16 16:17 UTC, hannut91 requested changes

2020-09-16 16:17 UTC, hannut91 commented on src/index.js
> +  }
`if`나 `switch`없이 이 문제를 해결할 수 있을까요?

2020-09-16 16:17 UTC, hannut91 commented on src/index.js
> +        resultNumber + String(inputNumber),
숫자를 뒤에 이어붙이기 위해 문자열로 형변환을 하신 것 같아요. 형변환없이 이 문제를 해결할 수 있을까요? 예를들어서 1인데 5를 누르면 15가되죠. 근데 사실 15는 10 + 5 입니다.

2020-09-16 16:17 UTC, hannut91 commented on src/index.js
> +      if (operator !== null) {
if안의 문장은 부정문이 되면 상당히 읽기가 어려워집니다.

previousNumber가 null이 아니고 operator가 null이 아니면
previousNumber가 null이고 operator가 null이면

이 두 문장을 읽어보시고 비교해보시면 좋을 것 같아요

2020-09-16 16:17 UTC, hannut91 commented on src/index.js
> +  }
지금 if가 중첩되어서 읽기가 어려운 것 같아요. guard clause 리팩터링을 해서 더 단순화 시키면 좋을 것 같아요.

```js
function handleClickOperator(inputOperator) {
  if (inputOperator === '=') {
    render(0, null, 0, calculate());
    return;
  }

  if (previousNumber === null) {
    render(afterNumber, inputOperator, 0, resultNumber);
    return;
  }

  if (operator === null) {
    render(calculate(), inputOperator, 0, resultNumber);
    return;
  }

  render(calculate(), inputOperator, 0, calculate());
}
```

See also
  - https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html

2020-09-17 10:26 UTC, JamieShin0201 commented on src/index.js
> +      if (operator !== null) {
이중 부정문을 사용하니 가독성이 매우 떨어지네요... ㅠ.ㅠ

2020-09-17 10:26 UTC, JamieShin0201 commented on src/index.js
> +  }
알려주신 방법으로 리팩토링하니 코드가 깔끔해졌습니다 ㅎ.ㅎ

2020-09-17 10:28 UTC, JamieShin0201 commented
안녕하세요~!

1. 이중 부정문을 수정하였습니다.
2. 이중 조건문을 수정하였습니다. 
3. if, switch 없이 calculate 하는 것은 조금 더 고민해보겠습니다.

감사합니다^^

2020-09-17 12:42 UTC, JamieShin0201 commented
1. operator 변수에 연산기호가 아닌 연산함수를 저장하였습니다.
2. calculate 함수를 삭제하고 사칙연산 함수를 만들었습니다. (4가지 함수).

개인적으로 코드가 보기 더 복잡해진 것 같아.. 좋은방법을 더 생각해보겠습니다.!!
감사합니다^^

2020-09-17 15:37 UTC, hannut91 requested changes

2020-09-17 15:37 UTC, hannut91 commented on src/index.js
> +}
`previous`와 `after`란 의미가 이해하기 어렵습니다. 단순하게 x, y는 어떤가요?

2020-09-17 15:37 UTC, hannut91 commented on src/index.js
> +        </button>
비슷한 코드들이 반복되고 있는 것 같아요. 어떻게하면 중복을 제거할 수 있을까요?

2020-09-17 15:37 UTC, hannut91 commented on src/index.js
> +  }
`inputNumber`에서 `input`이 의미하는바가 무엇인가요? `input`이 없으면 함수를 이해하는데 어려울까요?

2020-09-17 15:37 UTC, hannut91 commented on src/index.js
> +  }
```js
function handleClickNumber(number) {
  const nextNumber = (
    afterNumber === null
      ? 0
      : resultNumber * 10
  ) + inputNumber;
  render(previousNumber, operator, nextNumber, nextNumber);
}
```

엄청 마음에 들진 않지만 이렇게 다음에 바뀌는 숫자가 어떻게 만들어지는지 더 의도를 드러낼 수 있을거에요

2020-09-17 15:37 UTC, hannut91 commented on src/index.js
> +      null, operator(previousNumber, afterNumber));
비슷한 모양이 반복되는 것 같은데 여기도 중복을 제거할 수 있는 방법이 있을까요?

if로 분리하다보니 해당 함수가 4가지 일을 하고 있는 것처럼 보여요.

2020-09-18 04:15 UTC, JamieShin0201 commented on src/index.js
> +  }
다음과 같이 코드를 작성하면 handleClickNumber 함수내에 render함수를 1번만 사용하면 되고, 또 nextNumber를 한번만 구하면 되니 훨씬 간단해지는 것 같습니다.

감사합니다^^

2020-09-18 05:35 UTC, JamieShin0201 commented
안녕하세요.^^

1. 반복된 버튼 코드를 삭제하기 위하여 사친연산함수를 배열에 담았습니다.
2. 변수명을 조금 더 명확하게 지었습니다.
3. handleClickNumber 함수를 알려주신 방법대로 중복을 제거하고 조금 더 명확하게 리팩토링 하였습니다.

4. 어떻게 하면 중복을 제거할 수 있을지 계속 생각해보겠습니다~!!

2 + 2 = 4 를 할때
operator: + (이전에 입력한 연산기호)
inputOperator: =

이렇게 저장하기 위해서 변수를 나누었는데 괜찮을까요???

2020-09-18 14:23 UTC, JamieShin0201 commented on src/index.js
> +      null, operator(previousNumber, afterNumber));
계속 생각해보고 있는데.. 어려움이 있어 답글 남깁니다.

render 함수의 매개변수 4개를 조건에 따라 변경해서 
코드상 중복된 render함수를 한번만 작성하는 방식으로 바꾸려고 했는데요. 

그렇게 되면 render함수를 실행하기 전 여러 조건들을 실행하게 되어 빠른 return이 되지 않을거 같습니다.

다른 방법을 생각해보는게 좋을까요??

2020-09-18 15:01 UTC, hannut91 requested changes

2020-09-19 04:40 UTC, ahastudio commented
JavaScript의 OR는 독특한 사용법이 있습니다. 익숙하다는 전제로, 잘 활용하면 더 단순하고 이해하기 쉬운 코드가 됩니다.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR

2020-09-19 12:25 UTC, JamieShin0201 commented
안녕하세요~~^^

1. 사직연산 함수를 arrow function으로 변경하였습니다.
2. render() 함수의 파라미터를 객체로 변경하였습니다.

1) arrow function으로 변경하니 불필요한 키워드를 쓰지 않아도 되고 문장이 짧아져서 가독성이 좋아졌습니다.
2-1 ) 파라미터수가 많아 객체로 변경하니 복잡해보이던 코드가 보기좋아졌습니다.
2-2)  render 함수에 파라미터를 보낼때 변한값만 넣어주면 되니 편리해졌습니다. 
ex) render({ resultNumber: operator(previousNumber, afterNumber) });


OR 함수에 대해서 알아보고 제 코드에 적용할 부분이 있다면 적용해보도록 하겠습니다.
감사합니다 ^_^

2020-09-19 12:58 UTC, JamieShin0201 commented
render 함수의 매개변수를 3개로 줄여보았습니다.

 1. beforeInput: 이전 입력이 숫자인지, 연산자인지 확인하기 위한 함수
 2. operator: 연산자를 기억하기 위한 변수
 3. result: 화면에 결과값을 보여주기 위한 변수

감사합니다.^^

2020-09-19 14:29 UTC, hannut91 requested changes

2020-09-19 14:29 UTC, hannut91 commented on src/index.js
> +  }
`beforeInput`이 숫자를 다룰수도 있고 문자열도 다룰 수 있다보니 처리가 복잡해진 것 같아요. 계속해서 타입을 체크해줘야 하니까요. 다른 방법을 생각해보는게 좋을 것 같아요. 연산자를 저장하는 변수와 숫자를 저장하는 변수를 나누는건 어떨까요?

2020-09-19 14:29 UTC, hannut91 commented on src/index.js
> +  function handleClickOperator(inputOperator) {
`inputOperator`에서 `input`이 입력한 값을 나타내는 것 같아요. 이 함수를 사용할 때는 입력된 operator니까 괜찮아 보이는데, 매개변수에서는 이러한 context가 더 혼동이 되는 것 같아요. 그냥 operator를 사용하는건 어떨까요? 이미 operator를 사용하고 있다면 operator가 더 scope가 기니까 이 안쪽은 그냥 value정도로 써줄 수 있을 것 같아요

2020-09-20 08:07 UTC, JamieShin0201 commented
안녕하세요 ^^

1. handleClickOperator 함수 안에 매개변수 이름을 value로 변경하였습니다. 
2. beforeInput이라는 변수에 여러타입의 변수를 담아 사용하기 때문에 매번 타입을 체크해야 하는 불편함?, 자료형의 불명확성? 이 있습니다. 이 부분을 수정하였습니다. (매개변수를 줄이려고 이런 선택을 했었는데 좋은 방법이 아닌거 같네요..)

render의 매개변수
1. beforeResult : 중간 연산결과를 저장
2. operator : 연산자를 저장
3. result : 화면에 보여주기 위한 결과를 저장
4. pointer : pointer에 따라 숫자를 입력해야 하는지? 연산자를 입력해야하는지? 연산을 해야하는지? 확인할 수 있습니다.

변수의 이름을 정하는 것과 조금더 효율적인 코드, 보기좋은 코드를 작성하는게 아직 너무 어렵네요.ㅠㅠ
그리고 제가 실수로 지금 pull request도 main으로 보냈는데 지금 수정해서 다시 보낼까요??

2020-09-20 13:28 UTC, hannut91 approved these changes
고생하셨습니다 ㅎㅎ처음 작성한 코드와 마지막 코드를 비교하면서 어떤 변화가 일어났는지 보시면 좋을 것 같아요.
앞으로도 좋은 코드를 작성하는 연습을 많이 할 수 있으니 계속해서 잘 따라와주시면 좋을 것 같습니다.

과제풀이 영상을 통해서 다시 한 번 복습하면 좋을 것 같아요. 특히 아샬님은 어떻게 문제를 풀어나가는지 풀이과정을 눈여겨 보시면 좋을 것 같습니다.

2020-09-20 13:28 UTC, hannut91 commented on src/index.js
> +    if (pointer === 2) {
숫자2를 나타내는 것이 무엇인지 이해하기 어려운 것 같아요. 왜 숫자 2인지 설명이 되지 않기 때문이에요. 왜 1이나 3은 안되는지 이것만 봐서는 전혀 이해하기 어렵죠. 이러한 것을 Magic Literal이라고 부르는데, 리팩터링을 통해 없애면 좋을 것 같습니다.

See also
  - https://refactoring.com/catalog/replaceMagicLiteral.html

2020-09-20 13:28 UTC, hannut91 commented
이번 과제를 통해 무엇을 배우셨나요?

2020-09-20 13:28 UTC, hannut91 commented
회고는 이미 작성해주셨군요! 풀리퀘스트를 다시 보내주시면 머지하겠습니다!

2020-09-20 13:59 UTC, JamieShin0201 commented on src/index.js
> +    if (pointer === 2) {
말씀해주신대로 1이 뭔지 2가 뭔지 코드만 봐서는 이해하기 어렵겠네요.! 수정하였습니다.!

2020-09-20 14:08 UTC, JamieShin0201 commented
이번 과제를 통해서 

1. 변수와 함수 네이밍을 왜 잘해야하는지 알게되었습니다. 
2. arrow function을 이용하는 법을 알게 되었습니다.
3. 삼항연산자를 어느 부분에 적용하면 좋을지에 대해 알게 되었습니다.
4. 중첩된 if문 작성을 하지 않기 위한 guard clause에 대해 알게 되었습니다.
5. magic literal를 통해 변수를 명확하게 표현하는 법에 대해 알게 되었습니다.

내일 풀이강의를 보며 아샬님은 어떻게 이 과제를 풀어나가시는지  보고 배우겠습니다. 
그리고 아직 많이 부족하지만 1주차 2주차 ... ~ 매주매주 좋은 습관들을 익혀나가도록 노력하겠습니다ㅎㅎ

감사합니다^_^

2020-09-21 15:15 UTC, closed without merging