week2- 계산기 구현하기
CodeSoom/week1-assignment-2 pull request #40
Opened 2020-09-17 14:48 UTC by bbhye1

### **구현할 기능들**
숫자를 누르면 누른 숫자가 출력되어야 합니다.
숫자를 연속해서 누르면 숫자가 더해져서 출력되어야 합니다.
숫자와 연산자를 입력한 후 =를 클릭하면 계산 결과가 출력되어야 합니다.
연속해서 숫자와 연산자를 입력하면 중간에 계산 결과가 출력되어야 합니다.

### **중간 구현 내용_**
버튼 구현 완료
숫자를 연속해서 클릭시 숫자가 더해져서 하나의 숫자로 만들기 :  combineNumber함수
연산자를 클릭할때 두번째 연산자 클릭부터 앞전 계산을 실행시키기: calculateNumbers 함수
숫자와 연산자 클릭 후 =를 클릭하면 계산 결과 출력하기 완료 

### **미해결 부분**
number 파라미터에 재할당을 하지않고 대체할 수 있는 방법찾기 
중간에 연산자를 두번누르거나 연산자부터 누르거나 하는 예외처리하기
비슷한 파라미터 이름을 명확히 구분할수있게 다시 짓기

2020-09-17 15:41 UTC, hannut91 requested changes

2020-09-17 15:41 UTC, hannut91 commented on src/index.js
> +      numbers.push(num);
`push`명령어는 numbers의 값을 직접 고칩니다. 변수가 중간에 바뀌는거죠. 그러면 코드가 어떻게 동작할지 예측하기가 굉장히 어려워집니다. 이는 과제 1에서 배운 것을 상기해보시면 좋을 것 같아요

2020-09-17 15:41 UTC, hannut91 commented on src/index.js
> +    switch (calculateContent[1]) {
`switch`나 `if`없이 이 문제를 해결할 수 있을까요?

2020-09-17 15:41 UTC, hannut91 commented on src/index.js
> +    switch (calculateContent[1]) {
[1]이 무엇이고 [0], [2]가 무엇인지 가늠하기 어려운 것 같아요. 디스트럭처링을 사용하면 의도를 더 드러낼 수 있을거에요.

```js
function calculateNumbers() {
  const [x, operator, y] = calculateContent;

  switch(operator) {
    case '+':
      return x + y;
  }
}
```

See also
  - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

2020-09-17 15:41 UTC, hannut91 commented on src/index.js
> +          >
너무 복잡한 로직이 중간에 있어서 코드가 읽기 어려운 것 같아요. 핸들러 함수로 분리하면 어떨까요?

2020-09-17 15:41 UTC, hannut91 commented on src/index.js
> +          }}
여기도 마찬가지로 로직이 있는 함수를 핸들러 함수로 분리하는건 어떨까요?

2020-09-18 07:25 UTC, bbhye1 commented
**중간 작업 현황**

1. element에서 onClick 함수들을 모두 바깥으로 빼서 element가 간결하게 보일 수 있도록 했습니다. 함수들을 리팩토링 할 때 마지막 결과버튼의 함수내용의 길이가 한줄밖에 없어서 다시 onClick안으로 직접 넣어줬다가 나중에 예외처리때문에 코드가 길어져 다시 바깥으로 뺐습니다. 

2. if문이나 switch문을 대체하기 위해 오브젝트를 이용해서 값을 리턴해주었습니다. 

3. 재할당 방지를 위해 저번 과제와 마찬가지로 render 함수에 직접 파라미터 값을 넣어주었는데 버튼을 클릭할 때 연산자 버튼을 눌러야지만 숫자가  calculateContent에 넣어지도록 해서 combinedNumber에 문제가 없도록 했습니다. 
 그러나 여기서 calculateNumbers 함수에 세번째 인자가 전달이 안되는 문제가 생겨 파라미터로 현재값을 전달해주어 해결했습니다. 

4. 변수명을 중간중간 더 의미가 정확하다고 생각하는 것으로 변경했습니다. 

5. 오류가 나는 상황들을 처리해주었습니다. 
 -  연산자를 연속으로 누를 경우, 숫자에는 영향이 가지 않고 다시 숫자를 눌렀을 때 마지막으로 선택했던 연산자로 계산이 진행 
 될 수 있도록 했습니다.  
 -  처음에 연산자를 누를경우, 첫번째 숫자의 기본값으로 0을 설정해주어 계산이 계속 진행될수있게 해주었습니다.
 -  식이 완성되지 않았는데 결과버튼을 누르는 경우, 초기화 시켜주었습니다.

6. 커밋을 조금 더 의미있고 자세히 작성하려고 노력했습니다. 이번 과제의 초반 커밋들이 너무 광범위한 메세지에 통으로 한번에 올려서 신경쓰였는데  협업을 진행할때 계속 리팩토링을 할때도 통으로 고쳐서 올리면 다른 사람들이 어디를 어떻게 변경했는지알기 힘들것 같아 최대한 커밋을 쪼개서 올려봤습니다. 아직 영어가 많이 부족해 커밋 메세지가 좀 어색하진 않을까 고민이 되기는 하는데 이렇게 코딩과 영어공부를 한꺼번에 해결하는 욕심을 내보려구 합니다 ㅎㅎㅎㅎ.

2020-09-18 15:24 UTC, hannut91 requested changes

2020-09-18 15:24 UTC, hannut91 commented on src/index.js
> +  };
```js
render(result, 0, 0, '');
```

이부분만 보면 render에 어떤 값을 넘기는지 알기가 어렵습니다. 이런 경우 파라미터를 객체로 만들면 해결이 됩니다.

```js
render({
  currentNumber: result,
  currentNumber: 0, 
  previousNumber: 0, 
  storedOperator: '',
});
```

1. named parameter처럼 파라미터에 이름을 붙이는 것처럼 표현력이 좋아집니다.
2. optional한 값을 다루기가 쉬워집니다.
3. 의미있는 파라미터들을 객체로 묶을 수 있습니다.

See also
  - https://github.com/hannut91/refactoring-practice/tree/master/6.8-introduce-parameter-object
  - https://refactoring.com/catalog/introduceParameterObject.html

2020-09-18 15:24 UTC, hannut91 commented on src/index.js
> +  };
`if`, `else`를 사용하는 대신에 Guard Clause를 이용해서 리팩터링 해보시면 더 간단하게 표현할 수 있을거에요

See also
  - https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html

2020-09-18 15:24 UTC, hannut91 commented on src/index.js
> +      const combinedNumber = Number(currentNumber + number.toString());
두개의 숫자를 이어 붙이기위해서 형변환을 하신 것 같아요. 형변환 없이 이 문제를 해결할 수 있을까요? 예를들면 1 과 5을 누르면 15가 되는데, 15는 사실 10 + 5죠

2020-09-18 15:24 UTC, hannut91 commented on src/index.js
> +  };
`calculateNumbers`를 바깥으로 빼면 이 함수는 다른 곳에서도 재사용할 수 있고, 테스트하기 쉬워질거에요.

```js
const operators = {
  '+': x + y,
  '-': x - y,
  '*': x * y,
  '/': x / y,
};

const operator = '+';
operators[operator](3, 5); // 8
```

2020-09-19 01:59 UTC, bbhye1 commented on src/index.js
> +  };
이렇게 객체로 넣어주는것이 모든 렌더링 함수를 호출하는 부분에 해당이 될까요?? 확실히 어느 부분에 어떤 값을 넣어주고 있는지 확인할 수 있지만 코드가 길어지는것 같아서요! 코드가 길어진다 싶으면 항상 망설여지고 간결하게 줄이려고 노력하게 됩니다. ㅜㅜ

2020-09-19 02:19 UTC, hannut91 commented on src/index.js
> +  };
코드가 길어지긴 하지만 표현력이 좋아지니 저는 더 좋은 것 같아요 ㅎㅎ 선택의 문제인 것 같아요. name parameter를 쓸 필요 없이 자명하게 이해할 수 있다면 사용하지 않아도 되지만, 각 파라미터가 어떤 역할을 하는지 의도를 더 드러내고 싶다면 사용하면 좋을 것 같아요. 

코틀린이나 다른 언어들은 named parameter를 지원해서 `redner(currentNumber = 10)`이렇게 할 수 있지만 자바스크립트에는 이러한 문법이 없어서 객체를 아주 많이 이용합니다.

2020-09-19 02:20 UTC, bbhye1 commented on src/index.js
> +  };
저 부분을 calculateNumbers 함수가 아닌 render함수의 지역변수로 선언하라는 말씀이신가요?? 함수도 render함수 안에서는 재사용이 가능하다고 생각하는데 제가 잘 이해를 못한것같습니다ㅜㅜ;;

2020-09-19 07:46 UTC, bbhye1 commented
**중간 구현 내용**

1. 아래의 오류상황을 다루는데 이전 방법이 좋을 것 같아 커밋을 revert했습니다. 
- 연산자를 연속으로 누를 경우, 숫자에는 영향이 가지 않고 다시 숫자를 눌렀을 때 마지막으로 선택했던 연산자로 계산이 진행
될 수 있도록 했습니다. 

3. calculateNumbers 함수를 render함수 밖으로 빼주어 화면을 구현하는 기능과 숫자를 계산하는 기능을 분리했습니다. 

2. if문에서 else를 쓰지 않기 위해 Guard Clause를 사용해서 리팩토링해주었습니다.

3. 두개의 숫자를 붙이는 로직을 형변환없이 단순하게 바꾸어주었습니다.

4. (문제의 파라미터 객체화) 파라미터 객체화를 시켜주었습니다.  아직은 코드가 짧아 사실 코드가 길어지는게 복잡해졌다는 느낌이 들기도 했는데 확실히 코드를 읽어 내려갈 때 내가 어떤 파라미터를 어떤위치에 전달해주고 있는지 위로 올라가서 위치를 확인해보지 않아도 바로 읽힐 수 있는점이 큰 장점으로 다가왔습니다. 코드가 길어진다면 필요한 작업인것같습니다.

2020-09-19 11:02 UTC, ahastudio commented on src/index.js
> +    const combinedNumber = (currentNumber * 10) + number;
`currentNumber` 검사를 이 라인에 적절히 합쳐줄 수 있다면 불필요한 `if`문을 제거할 수 있습니다.

2020-09-19 12:00 UTC, bbhye1 commented on src/index.js
> +    const combinedNumber = (currentNumber * 10) + number;
삼항 연산자로 대체해서 if문을 제거해 주었습니다. 그러다보니 이미 제가 handleClickResult함수에서는 삼항 연산자로 if문을 제거해주었는데 다른 함수들에서는 간과했다는걸 깨달았습니다. 항상 더 꼼꼼해져야 한다는걸 느낍니다.

2020-09-19 14:35 UTC, hannut91 requested changes

2020-09-19 14:35 UTC, hannut91 commented on src/index.js
> +    const combinedNumber = currentNumber ? (currentNumber * 10) + number : number;
3항 연산자대신 null 병합연산자를 사용하면 다음과 같이 표현할 수 있습니다.
```js
const combinedNumber = (currentNumber ?? 0) * 10  + number;
```

See also
  - https://ko.javascript.info/nullish-coalescing-operator

2020-09-19 14:35 UTC, hannut91 commented on src/index.js
> +
여기 빈 줄이 두 줄이 들어갔네요

2020-09-19 14:35 UTC, hannut91 commented on src/index.js
> +function render({ displayedNumber, currentNumber, calculateContent }) {
연산할 연산자와 숫자를 가지고 있는 배열을 만들어서 문제를 해결해주셨네요. 배열이란 것은 원래 같은 형식의 값들의 순서가 있는 데이터 형식인데 지금은 문자열과 숫자를 각각 가지고 있고, 그리고 index 0이 연산자 index 1 이 숫자를 나타내고 있는 것 같아요. 

배열 대신에 객체로 표현하는건 어떨까요? 그러면 index 0 대신에 연산자로 접근하여 어떤 값을 나타내고 있는지 명확히 알 수 있을거에요

2020-09-19 15:46 UTC, ahastudio commented on src/index.js
> +    const combinedNumber = currentNumber ? (currentNumber * 10) + number : number;
오, 이거 좋네요. 👍

2020-09-20 03:14 UTC, bbhye1 commented
**중간 구현 내용**

3항 연산자 대신 null 연산자로 코드 길이를 줄여주었습니다. 

또 말씀해주신 배열대신 객체로 표현을 해봤는데 여기서 calculateNumbers함수는 재사용을 위해 건드리지 않고 넣어주는 파라미터들을 수정했습니다. 여기서 객체가 길어질 경우도 생각을 해봤는데 정확히 어느자리에 어떤 파라미터 값이 들어가는지 명시하는게 더 좋을것같아 forEach가 아닌 하나씩 직접 넣어주었습니다.

2020-09-20 07:05 UTC, bbhye1 commented
파라미터 객체화를 완성하고 보니 caculateContent로 묶어주지 않아도 예외상황에 대한 처리가 문제없이 이루어진다는것을 알았습니다ㅜㅜ. 그래서 caculateContent의 내용들을 풀어서 render함수의 파라미로 직접 넣어주었습니다.  설명을 들었어도 아직 리펙터링하는게 익숙치가 않아 그부분은 커밋하지 못했습니다. 리펙터링에 대해서는 더 연습하겠습니다.

2020-09-20 13:30 UTC, hannut91 approved these changes
고생하셨습니다 ㅎㅎ처음 작성한 코드와 마지막 코드를 비교하면서 어떤 변화가 일어났는지 보시면 좋을 것 같아요.
앞으로도 좋은 코드를 작성하는 연습을 많이 할 수 있으니 계속해서 잘 따라와주시면 좋을 것 같습니다.

과제풀이 영상을 통해서 다시 한 번 복습하면 좋을 것 같아요. 특히 아샬님은 어떻게 문제를 풀어나가는지 풀이과정을 눈여겨 보시면 좋을 것 같습니다.

2020-09-20 13:30 UTC, hannut91 commented
주간회고 채널에 회고를 올려주셧으니 머지하겠습니다!

2020-09-20 13:30 UTC, merged