[Week 1] Assignment 2 - 간단한 계산기 만들기
CodeSoom/week1-assignment-2 pull request #41
Opened 2020-09-17 16:19 UTC by wjy5446

# 1강 JSX - 1주차 과제 2

## 요구사항
[x] ESLint를 돌린 결과 아무런 문제가 없어야 합니다.
[x] 모든 인수 테스트를 통과시켜야 합니다.

## 구현할 기능들
[x] 숫자를 누르면 누른 숫자가 출력되어야 합니다.
[x] 숫자를 연속해서 누르면 숫자가 더해져서 출력되어야 합니다.
[x] 숫자와 연산자를 입력한 후 =를 클릭하면 계산 결과가 출력되어야 합니다.
[x] 연속해서 숫자와 연산자를 입력하면 중간에 계산 결과가 출력되어야 합니다.

## 작업 내용
[x] 여러개 버튼 생성 함수  생성 
[x] 숫자 버튼 클릭 함수 생성
[x] 연산자 버튼 클릭 함수 생성
[x] render 상태 값 생성 (총 4개 생성)

**render 상태값**

- showValue : 화면에 출력할 값
- resultValue : 계산된 결과 값
-> `=` 연산자으로 초기화 하거나 새롭게 숫자 버튼 클릭할 때, 실제 결과 값과 출력되는 값이 다르게 나와야 되는 경우 발생. 그러므로 따로 상태 값을 관리.  

- prevOp : 이전에 클릭한 연산자 버튼 값
-> 연산자 버튼 클릭시 이전 연산자를 이용해서 계산하고 결과값을 보여주여야 함. 그러므로 이전에 클릭한 연산자 값 저장

- reset : 숫자 버튼 클릭시 reset 여부
-> 숫자버튼 클릭시 누른 숫자로 reset해야 되는 경우와 이전에 입력한 숫자에 더해야 되는 경우가 존재. 그러므로 이를 reset 상태 값으로 관리

**함수**

- generateButtons(btnsArr, onClickHander) : 버튼에 표시할 텍스트 배열과 event 함수를 입력으로
  받아서 결과값으로 여러개의 버튼 태그를 생성하는 함수
-> 연산자 버튼을 생성하는 로직과 숫자 버튼을 생성하는 로직이 같아서 하나의 함수로 합쳐서 생성.

- calculate(num1, num2, op) : 두 숫자와 연산자를 입력으로 받아서 연산된 값을 반환하는
  함수 

- handleClickNumberBtn(number) : 숫자 버튼을 클릭했을 때 event 함수
- handleClickOpBtn(op) : 연산자 버튼을 클릭했을 때 event 함수

## 질의 & 상태
- 간단한 계산기 작성 코드이지만 상태값을 많이 필요하다는 것을 느꼈고, 이렇게 하는 게 맞는 지 싶네요.
- 이벤트 함수명을 작성할 때, handleClickNumberBtn으로 작성했는 데, 너무 긴 것 같네요.
- calculate 함수 작성할 때, switch문에서 eslint가 indent를 모두 같은 위치로 잡는 데 이게 맞는 지 모르겠네요.
- calculate 함수에서 switch문의 default를 에러를 발생시킬려고 throw를 사용했는 데, 이런 경우에는 어떤 방식으로 처리하는 지 궁금합니다.
- 많은 피드백 부탁드리겠습니다. 😄

2020-09-18 17:48 UTC, Kihyun92 requested changes
리뷰가 많이 늦었네요.. ㅠㅠ 🙏
같은 기능을 하는 코드를 함수로 만들어 쓰거나 하는 방식에 익숙하신 것 같아요! 과제의 의도 중 하나인 불변성을 유지하는 상태값을 사용 하는 법도 알고 계신듯 하구요. 좋습니다 :)

다만, 전반적으로 변수명, 함수명을 지을때 고민을 조금 더 해보시면 좋을 것 같습니다. 단순히 변수명을 이쁘게 짓는 것 보다, 이 함수/변수가 어떤 역할을 하고 있는지 파악을 하다보면 자연스레 코드 리펙터링이 이뤄질 것 같네요~🔥

그리고 상태값이 많다고 느껴질때는, 값들을 의미 있게 묶을 수 있는 객체를 사용해보는 것도 좋을것 같습니다. :)

2020-09-18 17:48 UTC, Kihyun92 commented on src/index.js
> +function render(showValue = 0, resultValue = 0, prevOp = '+', reset = true) {
`prevOp`와 같이 굳이 줄여서 표현할 필요는 없습니다. 변수명을 짧게하고 작업 내용에 prevOp에 대한 설명을 추가로 적는것보다, 변수명만 보더라도 어떤 역할을 하는지 알수 있도록 만드는게 좋을 것 같네요~

2020-09-18 17:48 UTC, Kihyun92 commented on src/index.js
> +        {generateButtons([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], handleClickNumberBnt)}
변하지 않을 값들은 따로 선언해둬도 좋을 것 같습니다~

2020-09-18 17:48 UTC, Kihyun92 commented on src/index.js
> +    default: throw new Error('ValueError');
switch문을 사용하지 않고 구현할 수 있는 다른 아이디어가 있을까요?😊

2020-09-18 17:48 UTC, Kihyun92 commented on src/index.js
> +    }
else문의 경우, 예측하기 힘든 코드를 만들 수 있게 합니다. 좀 더 간단하게 제어하는 방법이 없을까요?

2020-09-18 17:48 UTC, Kihyun92 commented on src/index.js
> +    if (op !== '=') {
조건문을 작성할 땐 부정문보다는 긍정문으로 작성하는게 이해하는데 좋을것 같습니다~

2020-09-18 17:48 UTC, Kihyun92 commented on src/index.js
> +    }
마찬가지로 `else` 없이 잘 표현하실 수 있을 것 같습니다 :)

2020-09-18 17:48 UTC, Kihyun92 commented on src/index.js
> +  function handleClickOpBtn(op) {
함수명, 파라미터 명 모두 자신만 이해되는, 추가 설명이 필요한 네이밍 같습니다~ 동료들에게 공유한다는 생각으로 조금 더 네이밍을 생각해보시면 더 완벽해질 것 같아요!!

2020-09-18 17:48 UTC, Kihyun92 commented on src/index.js
> +  function handleClickNumberBnt(number) {
함수명을 짓기가 어렵다고 느껴지는 경우는, 여러 요인이 있겠지만 해당 함수가 더 많은 기능을 수행하는 경우에 그렇습니다. 한번 이 함수가 어떤 역할을 하고 있는지 생각해보시면 좋을 것 같아요! :)

2020-09-19 05:19 UTC, wjy5446 commented on src/index.js
> +        {generateButtons([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], handleClickNumberBnt)}
의미를 가진 변수명으로 변하지 않을 값을 선언해주니, 
해당 코드를 읽을 때, 좀 더 이해가 잘되는 것 같네요 ㅎㅎ

2020-09-19 06:06 UTC, wjy5446 commented on src/index.js
> +    default: throw new Error('ValueError');
switch문을 대체할 수 있는 방법을 찾다가 Object literal lookup이라는 걸 찾았네요. 
아래 사이트를 참조해서 해당 방법으로 바꾸었습니다.

그런데 궁금한게, switch문을 사용하지 않는 이유가 명확하게 와닿지 않네요. 제가 명확하게 이해한 것은 switch문을 사용하면 case문 마다 break를 사용한다는 점입니다. 혹시 switch문을 사용하지 않는 이유가 있나요? 🤔 

참고 
https://ultimatecourses.com/blog/deprecating-the-switch-statement-for-object-literals

2020-09-19 08:15 UTC, wjy5446 commented
# 피드백 수정 사항 

## 변경사항
- [x] 상태값 변수명 변경
- [x] 이벤트 함수명 변경
- [x] 이벤트 함수 내 render 리네임밍
- [x] if else 문 제거
- [x] switch 문 제거
- [x] 변하지 않는 변수 따로 정의

## 디테일한 설명

1. 상태값 변수명 변경
- 기존의 `showValue`, `resultValue`, `preOp`, `reset`의 경우, 의미가 모호하여 변수명을 좀 더 표현력이 풍부하도록 변경

```
showValue -> displayNumber
resultValue -> bufferNumber
preOp -> bufferOperator
reset -> isEditableNumber 
```

- displayNumber : 화면단에 보여주는 값이라 display 사용. 또한 Value는 의미가 모호하기 때문에 Number라고 변경
- bufferNumber : 실제로 중간 중간 계산된 값을 저장하기 위해서 만든 상태 값이라서 buffer 사용. 기존의 result는 최종에 의미가 강하기 때문에 적절하지 않다고 판단하여 변경
- bufferOperator : 이도 위와 마찬가지로 중간에 누른 operator를 저장하기 위해서 만든 값이라서 buffer 사용
- isEditableNumber : reset은 초기화라는 의미인데, 실제로는 displayNumber을 누른 값으로 지정할 지 혹은 옆에 추가할 지에 대한 부분이라서 적절하지 않음 그래서 edit이라는 것을 사용해서 표현력이 높아지도록 변경

2. 이벤트 함수명 변경
- 기존의 `handleClickNumberBtn`, `handleClickOpBtn`의 경우, 의미가 모호하여 함수명 변경 

```
handleClickNumberBtn -> editDisplayNumber
handleClickOpBtn -> calculateBufferNumber
```

- editDisplayNumber : Number관련 버튼을 클릭했을 때, displayNumber가 변경되기 때문에 해당 이름으로 변경
- calculateBufferNumber : Operator관련 버튼을 클릭했을 때, bufferNumber가 계산되어 다시 정의 되기 때문에 해당 관련 이름으로 변경. 하지만 실제로는 bufferNumber이 계산되는 것 이외에 display로 보여주는 작업, 혹은 `=`일 때에는 초기화 작업도 발생하게 되는 데, 이렇게 네이밍을 하는 게 맞는 지는 모르겠네요.

3. 이벤트 함수 내 render 함수 리네임밍
- render 함수명만 사용하면 코드를 읽는 사람 입장에서 의미를 정확히 알지 못하기 때문에 render 함수명을 다시 지정.

```
caculateBufferNumber 함수 내에서 render에 대한 함수를 다시 정의하여 표현

const displayBufferNumber = () => render(bufferNumberNew, bufferNumberNew, operator, false);
const displayBufferNumberAndReset = () => render(bufferNumberNew, 0, '+', false);
``` 

- displayBufferNumber : `+`, `-`, `*`, `/` 일 때, 중간 계산 값을 보여주는 역활로 render가 사용되기 때문에 해당 이름으로 변경
- displayBufferNumberAndReset : `=` 일 때, 최종 계산 값을 보여주고, displayNumber 이외 상태값을 초기화하기 때문에 해당 이름으로 변경

4. if else 문 제거
- if else를 대신하여 guard clause를 적용. 
- 하지만 해당 방법은 예외처리를 위해서 사용되는 느낌이 강한데, `+, - , *, /`, `=`를 분기할 때, 사용하는 게 적절한지는 모르겠네요.

5. switch 문 제거
- switch 문 대신에 object literal lookup 사용

6. 변하지 않는 값 따로 변수 정의

2020-09-19 14:05 UTC, Kihyun92 requested changes
전반적으로 매우 고민하신 흔적이 느껴집니다👍
switch문을 권하지 않는 이유는 제 생각으로는 말씀하신대로 break, default등으로 인해 관리의 어려움이 있고 함수에서사용할 경우 함수에 보다 많은 역할을 하게하고 복잡성을 증가시켜 결국 사이드 이펙트로 이어질 가능성이 있다고 생각해서였습니다. 고민해보시고 더 나은 방안을 찾아가시는게 좋네요 😁

그리고 "컴퓨터 과학에서 가장 어려운게 캐시 무효화와 이름짓기다" 라는 말도 있더라구요. 과제를 하시면서 좋은 네이밍 습관을 가져가시면 좋겠습니다 :)

2020-09-19 14:05 UTC, Kihyun92 commented on src/index.js
> +  }
그리고 num1, num2라는 변수명도 의도를 알 수 없는 것 같아요. 차라리 방정식의 일종이니 x, y가 깔끔할 것 같아요~

2020-09-20 07:23 UTC, wjy5446 commented
# 피드백 수정 사항 2

## 변경사항
- [] 변하지 않는 상수 값 render 함수 밖에 정의
- [] calculate 함수 재정의
- [] map 함수를 이용한 버튼 생성
- [] 이벤트 핸들러 함수명 리네이밍

2020-09-20 08:45 UTC, wjy5446 commented on src/index.js
> +  const OPERATE_BUTTON_CONTENT = ['+', '-', '*', '/', '='];
어떤 용도로 사용하는 지도 알려주기 위해서 다음과 같이 명명 했는데, 이렇게 되다보니 코드가 복잡해보이는 감이 있네요. (어렵네요. 변수명 짓기 ㅎㅎ) 😄

그리고 해당 상수값을 render 함수 밖에 지정하는 이유가 있을 까요? 
저는 render에서 쓰이는 상수 값이기 때문에 render 안에 넣어주는 게 편할 것 같아서 안 쪽에다 정의했습니다. ㅎㅎ

2020-09-20 08:48 UTC, wjy5446 commented on src/index.js
> +  }
아래 처럼 lookup을 함수로 만들고, 해당 lookup을 바로 호출하는 형식으로 바꾸었습니다. 

```
// calculate 함수 lookup
const calculate = {
    '+': (x, y) => x + y,
    '-': (x, y) => x - y,
    '*': (x, y) => x * y,
    '/': (x, y) => x / y,
  };

//  호출
const result = calculate[operator](x, y);
```

2020-09-20 08:50 UTC, wjy5446 commented on src/index.js
> +  function editDisplayNumber(number) {
제가 너무 깊게 생각한 것 같네요 ㅎㅎㅎ 😄 
이벤트 함수 정의 관련해서 고민이 있었는데 참고해주신 자료로 도움이 많이 되었습니다.

2020-09-20 08:52 UTC, wjy5446 commented on src/index.js
> +function render(displayNumber = 0, bufferNumber = 0, bufferOperator = '+', isEditableNumber = false) {
슬랙에서 아샬님께서 추천해주신 RORO 패턴으로 코드 작성했습니다. ㅎㅎ

해당 코드로 작성해보니 확실히 이벤트 함수 내에서 render 함수를 사용했을 때, named parameter를 사용해서 코드를 읽는 사람 입장에서 무슨 의미인지 좀 더 직관적으로 이해가 가능한 것 같습니다. 

그래서 기존에 이해를 위해 작성 되었던 render 함수명 재정의 부분을 지울 수 있었습니다.

2020-09-20 08:56 UTC, wjy5446 commented on src/index.js
> +  function generateButtons(btnsArr, onClickHandler) {
추천해주신 대로 함수를 이용해서 버튼을 생성하는 것보다 바로 map함수를 적용하는 형식으로 코드를 수정했습니다. 

생각해보니 간단한 코드 같은 경우에는 제가 정의한 함수를 사용했을 때, 코드를 읽는 사람 입장에서 좀 더 이해가 힘들어 하는 경우가 발생했을 수도 있을 것 같다는 생각이 들었습니다. 

리뷰 감사드립니다. ㅎㅎ

2020-09-20 08:59 UTC, wjy5446 commented on src/index.js
> +    }
말씀해주신대로 OPERATE_BUTTON_CONTENT에 '='가 같이 있기 때문에 생기는 문제 였네요.;;;

그래서 `handleClickOperator`를 `handleClickBasicOperator`와 `handleClickEqualOperator`로 분리해서 코드를 작성했습니다. 

코드를 작성할 때, 너무 공통의 함수는 하나로 만들려는 강박 때문에 =도 같은 함수로 만들려고 해서 생긴 문제인 것 같네요. 무조건 하나의 함수로 만들려고 하기 보다는 역할이 다르면 다른 함수로 만들도록 해야 겠네요.

리뷰 감사드립니다.

2020-09-20 11:02 UTC, Kihyun92 commented on src/index.js
> +  const OPERATE_BUTTON_CONTENT = ['+', '-', '*', '/', '='];
render 내부에 있게되면, render 함수가 호출될때마다 항상 같은 값을 가짐에도 매번 선언, 할당되는 과정을 거치기 때문에 말씀 드렸던것 같아요~

2020-09-20 11:18 UTC, Kihyun92 requested changes
코드가 많이 깔끔해졌네요! 마지막으로 몇가지만 수정하면 될 것 같습니다 :) 
많은 고민을 하신 만큼, 더 많이 배우셨을것 같습니다 ㅎㅎ 조금 만 더 힘내시죠~

2020-09-20 11:18 UTC, Kihyun92 commented on src/index.js
> +/* eslint-disable object-curly-newline */
이 룰을 disable 하지 않고 문제를 해결할 수 없을까요? 이것도 주어진 과제의 목표 중 하나 입니다 :)

2020-09-20 11:18 UTC, Kihyun92 commented on src/index.js
> +  };
이 객체도 마찬가지로 render 함수 내에 있을 필요가 없어보입니다~

2020-09-20 11:18 UTC, Kihyun92 commented on src/index.js
> +    );
handleClickEqualOperator 함수에도 동일한 로직이 있는데, 함수로 추출하는건 어떨까요?

2020-09-20 16:27 UTC, Kihyun92 approved these changes
고생하셨습니다~ 적극적으로 질문해주시고, 열심히 하시는 모습에 저도 에너지를 받았던 것 같습니다.
이번 과제를 하면서 배웠던점이나, 아쉬웠던점을 한번 생각해보시면 좋겠습니다~
코드는 회고 해주시면 머지 할 예정입니다! 👍

2020-09-20 17:16 UTC, wjy5446 commented
# 피드백 수정 사항 2

## 변경사항
- [x] object curly newline
- [x] calculate 함수 render 함수 밖에 정의
- [x] operator 관련 이벤트 함수 리팩토링

2020-09-20 17:43 UTC, wjy5446 commented on src/index.js
> +/* eslint-disable object-curly-newline */
우선은 룰에 따라서 object에 newline을 추가하는 방식을 사용했습니다. 

코드를 변경해서 해당 문제를 해결하려고 했으나 어떻게 해야되는 지 도저히 모르겠네요;; 😢

2020-09-20 17:46 UTC, wjy5446 commented on src/index.js
> +  };
해당 함수도 밖으로 빼주었습니다.

이 역시도 상수와 마찬가지로 고정된 값이기 때문에 render 함수가 호출될 때마다 정의되고 호출되기 때문이라는 것을 알게 되었습니다.

2020-09-20 17:47 UTC, wjy5446 commented on src/index.js
> +    );
해당 코드를 함수로 추출해서 적용했습니다. ㅎㅎ

2020-09-20 18:21 UTC, wjy5446 commented
# 주간회고 

## 배운 점 

**1. 불변성 유지**

- 저번의 과제도 그렇고 이번 과제도 어떻게 불변성을 유지한 채 코드를 작성하는지가 핵심이였다. 불변성을 유지하여 코드가 어떻게 동작하는 지 예측가능하게 만들어 주어서 디버깅을 용이하게 만들어준다. 

- 이를 위해서 중요한 것이 함수형 프로그래밍처럼 코드를 작성해주는 것이 중요한 것 같다. 나중에 기회가 된다면 함수형 프로그래밍에 대해서 공부하는 것이 좋을 것 같다. 

**2. 변수명, 함수명 정의**

- 두번째 과제에서 가장 힘들었던 것이 적절한 변수명과 함수명을 정의하는 것이였다. 표현력을 높이기 위해서 긴 변수명을 사용해서도 않되고 간단하게 표현하기 위해서 짧은 변수명을 사용해서도 않된다. 적절한 용어를 사용하는 것이 좋다. (그게 어렵다.)

- boolean 함수명 정의 : 해당 함수명을 정의할 때에는 is + (명사, 과거분사, 현재진행형, 형용사)로 적용하는 것이 좋은 것 같다. 이때 is + (동사원형)은 사용하면 않된다.

- 이벤트 함수명 정의 : 이벤트 함수명을 명명할 때에는 handle + ~ 로 정의해주는 것이 좋다.

- 단축어는 되도록 쓰지 않는다. : num, op와 같은 단축어 보다는 numbers, operators와 같이 풀어서 작성하는 것이 좋다. 

**3. switch문은 Object literal lookup**

- switch문의 경우, case마다 break를 작성해주고, 함수에서 사용되면 많은 역할을 담당하여 함수는 하나의 역할만 담당한다는 규칙을 깨뜨릴 수 있고, 여러 역할을 하여 사이드 이펙트를 일으킬 경우가 많다.
- 이런 switch 문보다는 Object literal lookup을 사용하는 게 코드가 깔끔해 질수 있다.

**4. 상수, 계산이 고정된 함수는 render 함수 밖에 정의**

- 상수와 같은 변하지 않는 값을 render 안에 정의할 경우,  같은 값이지만 render 함수내에서 불필요하게 선언되고 할당되는 경우가 발생한다. 그렇기 때문에 외부에서 관리해주는 것이 좋다.

**5. if-else문 사용 자제**

- if-else문의 경우, switch문과 마찬가지로 함수내에서 함수가 여러 역할을 담당하게 만들기 때문에 사용하지 않는 게 좋고, 또한 else 부분에서 어떤 작업을 하는지 명확하고 알 수 없다는 단점을 가지고 있다.

- 만약 해당 문법이 예외처리쪽에 가까우면 guard clause를 사용하면 좋고, 이런 방식이 아니라면 함수를 분리하여 하나의 함수가 하나의 역할만 하도록 코드를 수정해주는 것이 좋다.

**6. RORO 패턴**

- 자바스크립트에서는 named parameter 개념이 존재하지 않는다. 그렇기 때문에 함수를 호출할 때, 전달되는 인수가 무엇인지 알기가 힘들다. 이를 해결하기 위해서 객체를 전달하고 객체를 받는 RORO 패턴을 사용해서 해당 문제를 해결할 수 있다.

- named parameter 이외에 RORO 패턴의 장점은 "Cleaner default parameters", "Richer return values". "Easy function composition"이 존재한다.

2020-09-21 13:39 UTC, kimkhyun commented
슬랙 > 주간회고 채널에 같이 공유해주세요~!

2020-09-21 13:41 UTC, Kihyun92 commented
@wjy5446 님, 슬랙 > 주간 회고 채널에도 공유해주세요~!!

2020-10-05 12:55 UTC, merged