week1-assignment-2
CodeSoom/week1-assignment-2 pull request #43
Opened 2020-09-18 01:18 UTC by comejtome508

**요구사항**

- [ ] 모든 인수테스트를 통과시켜야 합니다.

**구현할 기능들**

- [ ] 숫자를 누르면 누른 숫자가 출력되어야 합니다.
- [ ] 숫자를 연속해서 누르면 숫자가 더해져서 출력되어야 합니다.
- [ ] 숫자와 연산자를 입력한 후 =를 클릭하면 계산 결과가 출력되어야 합니다.
- [ ] 연속해서 숫자와 연산자를 입력하면 중간에 계산 결과가 출력되어야 합니다.

**현재 진행사항**
- 버튼 나열 후 누르는 경우 나타냄
- 숫자와 연산자 구분을 분기로 나눔
- 연산자 함수에서 switch를 사용해서 입력한 연산자에 따라 실제 연산 진행    

**이슈**
- 숫자의 경우 받으면 이전에 입력한 숫자가 있는가, 연산자가 있는가에 따라 분기를 나누어 진행예정
- 연산자를 누른 뒤에 연산자는 화면에 나타나지 않아야 함
- switch의 default 값에 과거 숫자 * 10 + 현재 숫자를 해줘야 할듯
- const의 value 값을 이용해서 할당을 받도록 하는데 이것이 최선인지 고민

2020-09-18 14:11 UTC, comejtome508 commented
**현재 진행사항**

버튼을 누르면 숫자를 표출
숫자를 연속해서 누르면 10의 자리, 100의 자리 숫자로 변경
연산자를 누르고 =를 누르면 결과값 도출까지 진행

**이슈**
기존의 로직과 할당해주는 object가 너무 복잡해서 새로운 방법으로 시도했습니다.
아직 연속해서 누른 경우의 로직을 세우지 못했습니다.

2020-09-18 16:50 UTC, wholemann commented
연속해서 누른 경우는 둘 중 하나죠. 숫자냐 연산자냐.

숫자가 연속으로 눌릴 경우 피연산자인 숫자가 어떻게 변해야 하나요?

3다음 3을 누르면 몇이 되나요? 33이죠. 이걸 달성하려면 어떤 처리가 필요한가요?

2020-09-18 16:51 UTC, wholemann commented on src/index.js
> +//   return value;
불필요한 주석은 제거하고 커밋해주세요!

2020-09-18 16:52 UTC, wholemann commented on src/index.js
> +  }else{
else, else if는 앞으로 개발 인생에서 몰아냅니다:)

영원히 안녕을 고하세요! else는 만악의 근원입니다. 벌써 엄청나게 복잡도가 올라갔고

코드의 예측 가능성이 매우 떨어졌죠. 무슨 일이 벌어지고 있는지 간단 명료하게 설명 가능할까요?

2020-09-18 16:52 UTC, wholemann commented on src/index.js
> +console.log(isNaN(tempValue.secondValue));
console도 제거해주세요. lint에서 warning 뜰 겁니다.

2020-09-18 16:53 UTC, wholemann commented on src/index.js
> +          <button type="button" onClick={() => render(j)}>
단순히 render 호출로 처리하고 있는데

숫자를 눌렀을 때, 연산자를 눌렀을 때 두 경우 처리해줘야 되는 일이 조금은 다를 겁니다.

이를 구체화 해보세요.

2020-09-18 16:54 UTC, wholemann commented on src/index.js
> +}
switch문 또한 else와 마찬가지로 절대 쓰지 않습니다ㅎㅎ

이 부분을 대체할 다른 아이디어는 없을까요? JS에선 아주 좋은 친구가 있죠.

2020-09-18 16:54 UTC, wholemann requested changes
일단 주석, switch, else, else if를 모두 몰아내보세요! 그게 먼저입니다:)

2020-09-18 23:54 UTC, comejtome508 commented
> 연속해서 누른 경우는 둘 중 하나죠. 숫자냐 연산자냐.
> 
> 숫자가 연속으로 눌릴 경우 피연산자인 숫자가 어떻게 변해야 하나요?
> 
> 3다음 3을 누르면 몇이 되나요? 33이죠. 이걸 달성하려면 어떤 처리가 필요한가요?

2020-09-19 05:35 UTC, comejtome508 commented on src/index.js
> +//   return value;
네!! 제거했습니다!

2020-09-19 05:36 UTC, comejtome508 commented on src/index.js
> +  }else{
이 부분은 
1. 입력한 것이 숫자인가 연산자인가를 판단합니다. 연산자가 입력되기 전까지는 무조건 연속된 숫자처리가 진행되도록 합니다.

2020-09-19 06:26 UTC, comejtome508 commented on src/index.js
> +  }else{
else, else if 대신 빠른 return로 작성해보았습니다~!

2020-09-19 13:03 UTC, comejtome508 commented on src/index.js
> +          <button type="button" onClick={() => render(j)}>
저는 시작할 때 'a 연산자 b =' 연산자를 눌렀을 경우에는

2020-09-19 13:07 UTC, comejtome508 commented on src/index.js
> +}
switch를 제거하고 map과 object를 써서 진행을 해보고 있는데 예상했던 것보다 오랫동안 잘 풀리지 않아서 계속 진행중입니다.....혹시 조언을 해주시면 감사하겠습니다...

2020-09-19 13:11 UTC, comejtome508 commented
> 연속해서 누른 경우는 둘 중 하나죠. 숫자냐 연산자냐.
> 
> 숫자가 연속으로 눌릴 경우 피연산자인 숫자가 어떻게 변해야 하나요?
> 
> 3다음 3을 누르면 몇이 되나요? 33이죠. 이걸 달성하려면 어떤 처리가 필요한가요?

re) 숫자 두개가 연속될 경우에는 10을 곱하고 이후에 들어온 값을 더해주는 것으로 처리했는데, 제 로직에서 '='를 누르지 않고 연속해서 다음 숫자를 누르는 경우 이전 값을 자동으로 연산을 해주는 것에 대한 로직을 더 고민해봐야 합니다

2020-09-19 14:42 UTC, Kihyun92 commented on src/index.js
> +          <button type="button" onClick={() => render(j)}>
연산자를 눌렀을때의 처리를 따로 함수로 구체화함으로써 의도하신 '연산자를 눌렀을 경우에는 무조건 b로 넘어가도록 분기를 설정'하지 않아도 되도록 하라는 말씀이신것 같습니다~
조건문이라는것 자체가 복잡성을 높이게 됩니다. 분기를 최소화 할 수 있는 방법이 있을 것 같네요 :)

2020-09-19 15:39 UTC, Kihyun92 requested changes
코드들이 조금 엉켜서 복잡해진것 같습니다! 고민은 많이 하신 것 같으니, 천천히 구현해야하는 목표들을 하나씩 정리하면서 작업해보셔도 좋을 것 같습니다~

2020-09-19 15:39 UTC, Kihyun92 commented on src/index.js
> +  const received = judgeNumber(value);
숫자버튼이나 연산자 버튼을 클릭시에 모두 render로 하나의 값만 넘기고 있고, 그걸 구분하기위해 judgeNumber(value)가 추가된것 같아요. 그러다보니 이 함수가 매우 매우 복잡해졌고, 너무 많은 역할을 수행하게 됐습니다.

수형 트레이너님 말씀처럼, 숫자 버튼과 연산자 버튼들이 눌렸을때 기능이 달라질 것 같아요. 인라인으로 렌더 함수를 호출하는 방식은, 이전 과제에서 매우 간단한 역할을 할 경우에는 허용가능 했지만, 지금 과제에서는 함수로 각 기능을 구체화 하는게 좋아보입니다!

2020-09-19 15:39 UTC, Kihyun92 commented on src/index.js
> +  console.log(`value2: ${received}`);
커밋 시에는 콘솔 로그 제거 부탁드려요.

2020-09-19 15:39 UTC, Kihyun92 commented on src/index.js
> +  if(isNaN(value) != true && isNaN(tempValue.secondValue) != true){
isNaN(value)와 같은 처리가 필요해진 원인이 무엇일까요? 한번 고민해보시면, 함수 분리할때 수월하실 것 같아요~

그리고 ==와 같은 동등 연산자가 아닌 ===와 같은 일치 연산자로 사용하셔야합니다.
(참고: https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Comparison_Operators)

2020-09-19 15:39 UTC, Kihyun92 commented on src/index.js
> +}
일단 calculResult가 두개가 있네요. 그리고 변수명은 줄여서 쓰는 것 보다 calculationResult와 같이 다 쓰는게 좋습니다. 가능하면 간결하고 명확한 네이밍을 고민해주세요.

그리고 계산결과를 리턴해주는 함수 내에 opValue를 가지고 있다가 넘겨받는 값에 따라 계산해거 Map에 가지고있을 필요가 있을까요?

2020-09-19 18:07 UTC, ahastudio commented
주석 대신 적절한 이름을 가진 함수를 만들면 코드를 정리하고 단순한 패턴을 발견하는데 도움이 됩니다.

https://refactoring.com/catalog/extractFunction.html

2020-09-20 09:57 UTC, comejtome508 commented on src/index.js
> +}
map 대신 object의 key와 value를 이용하였고 if문을 이용해서 분기를 나누어 연산처리를 진행하였습니다!

2020-09-20 10:02 UTC, comejtome508 commented on src/index.js
> +  if(isNaN(value) != true && isNaN(tempValue.secondValue) != true){
- 숫자와 연산자 버튼을 누르면 각각의 함수로 이동하게 진행했습니다.

2020-09-20 10:10 UTC, comejtome508 commented
**현재 진행사항**

- ESlint와 Test를 모두 통과함

**이슈**

- 변수의 이름을 범위에 따라서 더 구체적으로 하거나 간략하게 바꿔야함
- 글로벌 영역에 값이 할당되는 변수들을 없애야함
- ESlint 오류 자동 수정을 진행하다가 npm start를 할 경우 HTML 태그들이 노출되는 문제가 생김
- HTML영역에 있는 함수를 밖으로 빼내서 간단하게 해야함

( 더 간결한 코드로 수정하다가 에러가 계속 나서 일단 마지막으로 되돌렸습니다...ㅜ)

2020-09-20 12:02 UTC, Kihyun92 requested changes
조건문이 생기는 근본적인 이유에 대해서 고민해보시면 로직 개선에 많은 도움이 될 것 같습니다~ 조금만 더 힘내시죠👍

2020-09-20 16:30 UTC, Kihyun92 approved these changes
고생하셨습니다! 회고 남겨주신걸 보니, 이번과제를 하면서 여러가지를 배우고 느끼신것 같아 저도 기쁘네요 :) 
막히는 부분이 있다면 앞으로도 적극적으로 대화하며 함께 해결했으면 좋겠습니다~ 👍

2020-10-05 12:54 UTC, merged