[1주차] 간단한 계산기 만들기
CodeSoom/week1-assignment-2 pull request #46
Opened 2020-09-18 08:28 UTC by oceanide2

제목은 "간단한 계산기 만들기"이지만 전혀 간단하지 않았습니다. 

- 우선 계산을 위해서 입력되는 숫자와 연산자를 어떻게 처리해야할지가 전혀 감이 잡히지 않았습니다.
   혼자 생각하다가 머리도 아프고 과제를 제출하지도 못하는 것보다 차라리 다른 분들의 코드를 참조하여 이해하는 수준에서
   배껴라도 보자는 마음에서 다른 분들의 코드를 확인해봤습니다. 그 중에서 제가 가장 이해되는 방법을 기준으로 제가 할 수 있는 수준정도에서
   작성해봤습니다.

- const를 사용하여 코드를 작성하는 것이 코드를 재귀적으로 작성해야 하는 것 같아 보였는데, 이게 익숙하지가 않습니다.
   뭔가 상태를 저장해 나가는 방식으로만 생각이 떠오릅니다. 요구사항 또는 구현사항을 어떤 방식으로 시작해서 접근하기 쉬운것인지를
   고민하게 만듭니다.  1주차도 이리 쉽지 않은데 앞으로 남은 차수도 포기하지 않고 지속할 수 있을지가 걱정입니다.

2020-09-18 15:33 UTC, hannut91 requested changes

2020-09-18 15:33 UTC, hannut91 commented on src/index.js
> +function render(result = 0, input = [0]) {
`inputs`라고 이름을 지으면 변수만 봐도 여러개라는 것을 바로 드러낼 수 있을거에요

2020-09-18 15:33 UTC, hannut91 commented on src/index.js
> +    if (isStartCalculation(input) || isEqualOperator(operator)) {
함수의 이름이 오히려 이해하는데 더 어려운 것 같아요. 

```js
if (operator === '=') {}

if (isEqualOperator(operator)) {}
```

둘중에 어떤 것이 읽는 사람에게 있어서 더 확실하게 의도가 전달될까요?

2020-09-18 15:33 UTC, hannut91 commented on src/index.js
> +const deleteLastItem = (arr) => arr.slice(0, -1);
코틀린에서는 `dropLast`라는 이름을 사용하고 있는데 `dropLast`는 어떨까요?

See also
  - https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/drop-last.html

2020-09-18 15:33 UTC, hannut91 commented on src/index.js
> +const getLastItem = (arr) => arr[arr.length - 1];
배열 아이템중에 가장 마지막 것을 가져오는 함수인것 같아요. `last`라는 이름은 어떨까요?

2020-09-18 15:33 UTC, hannut91 commented on src/index.js
> +const isNumber = (v) => getType(v) === 'Number';
```js
const isNumber = (v) => typeof v === 'number';
```

는 어떨까요?

2020-09-18 15:33 UTC, hannut91 commented on src/index.js
> +      render(newNumber, [...deleteLastItem(input), newNumber]);
`newNumber`에서 `new`는 어떤 의미를 드러내나요?

2020-09-18 15:33 UTC, hannut91 commented on src/index.js
> +    }
`if`와 `else` 대신에 Guard Clause를 사용해서 표현하는건 어떨까요?

See also
  - https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html

2020-09-18 22:42 UTC, oceanide2 commented on src/index.js
> +};
고민해보도록 하겠습니다.

2020-09-18 22:48 UTC, oceanide2 commented on src/index.js
> +    if (isStartCalculation(input) || isEqualOperator(operator)) {
말씀하신 방식이 더 이해하기는 쉬워보입니다. 저걸할때는 isEqualOperator보다는 isStartCalculation이라는 이름이 더 이상하다고 생각이 들었습니다. 함수이름과 변수이름을 짓는 것은 항상 쉽지 않은 것 같습니다

2020-09-18 22:49 UTC, oceanide2 commented on src/index.js
> +function render(result = 0, input = [0]) {
복수로 표시하는 것이 맞네요. 말씀하신대로 수정하겠습니다.

2020-09-18 22:55 UTC, oceanide2 commented on src/index.js
> +const getLastItem = (arr) => arr[arr.length - 1];
말씀하신대로 적용하겠습니다. :)

2020-09-18 23:00 UTC, oceanide2 commented on src/index.js
> +const deleteLastItem = (arr) => arr.slice(0, -1);
이건 궁금해서 여쭤보는 것인데, 함수 이름을 변경하는데 코틀린을 언급하신 이유가 있으신지가 궁금합니다.

2020-09-18 23:32 UTC, oceanide2 commented on src/index.js
> +const isNumber = (v) => getType(v) === 'Number';
typeof 를 사용하라고 말씀해주신 것은 이유가 궁금합니다. 코드가 더 간단해서일까요?

2020-09-18 23:42 UTC, oceanide2 commented on src/index.js
> +    }
Guard Clause를 잘 쓰면 코드가 더 보기 쉬워지네요. 말씀하신대로 수정해보도록 하겠습니다.

2020-09-19 01:53 UTC, oceanide2 commented
- 말씀하신 수정사항을 적용해봤습니다. newNumber 변수이름은 어떤 이름으로 수정할지는 고민중이라 적용을 못했습니다.
  고민해보고 추가적용해보도록 하겠습니다.

- 질문 사항이 있습니다. 아래 코드에서 ```=== false```를 쓰는 방식이 더 좋을까요? 아니면 ```!```를 사용하여 줄이는게 더 좋을까요?
```
if ((isOperator(op) && isNumber(a) && isNumber(b)) === false) {
    return 0;
  }
```

2020-09-19 02:24 UTC, hannut91 commented on src/index.js
> +const deleteLastItem = (arr) => arr.slice(0, -1);
코틀린에서는 `dropLast`가 기본으로 메서드를 제공하고 있기 때문에 참고하면 좋을 것 같아서 언급했습니다. 자바스크립트에서는 기본으로 제공하지는 않죠. lodash를 예제로 언급할껄 그랬네요. lodash에서는 `dropRight`라는 이름으로 구현이 되어있네요

See also
  - https://lodash.com/docs/4.17.15#dropRight

2020-09-19 02:24 UTC, hannut91 commented on src/index.js
> +const isNumber = (v) => getType(v) === 'Number';
맞습니다

2020-09-19 02:27 UTC, hannut91 commented
해당코드만 봐서는 판단하기 어렵지만 `!`를 사용하는게 더 간단해보이긴 합니다!

2020-09-19 06:34 UTC, oceanide2 commented
- newNumber 변수이름은 calculatedNumber로 변경해보았습니다.
- if 구문에서 ```false```대신에 ```!```를 사용하는 것으로 변경했습니다.

추가적인 수정이 필요한지 다시 한번 확인 부탁 드립니다.

2020-09-19 14:40 UTC, hannut91 requested changes

2020-09-19 14:40 UTC, hannut91 commented on src/index.js
> +      render(newResult, [newResult, operator]);
`newResult`에서 `new`는 어떤 의미를 가지고 있나요? `new`가 없어도 이해할 수 있을까요?

2020-09-19 14:40 UTC, hannut91 commented on src/index.js
> +function render(result = 0, inputs = [0]) {
배열이란 것은 원래 같은 연속되는 데이터 형식을 나타내는 자료형인데 지금은 숫자도 다루고 있고 문자열도 다루고 있다보니 복잡해진 것 같아요. 계속 타입을 확인해야 하구요. 그리고 순서가 굉장히 중요해서 0 인덱스는 숫자를 나타내고 인덱스 1은 연산자를 나타내고 있어요. 

배열 대신에 객체로 나타내는건 어떨까요?

2020-09-19 14:40 UTC, hannut91 commented on src/index.js
> +  };
숫자도 아니고 오퍼레이터도 아닌 경우는 어떤경우가 있나요?

2020-09-19 18:25 UTC, ahastudio commented
이름을 지을 때 먼저 우리 말로 설명하고 자연스럽게 영어로 옮기는 게 의도를 드러내기 좋습니다. 예를 들어 `isStartCalculation`는 이름과 구현 모두를 봐도 바로 알기 어렵습니다. 실제로 사용되는 곳에서 가서 생각해야 “버퍼가 꽉 찼는지, 또는 계산할 준비가 됐는지 확인해서 (👈여기까지가 이 함수의 용도) 계산을 통해 버퍼를 단순화해 다음 연산자를 받을 수 있게 해주는구나”라고 이해할 수 있게 되죠. 전자라면 상수로 버퍼 사이즈를 잡아주고 full 여부를 확인할 수 있고, 후자라면 ready 등을 쓸 수 있죠.

2020-09-21 15:16 UTC, hannut91 commented
회고를 남겨주셨으므로 머지합니다!

2020-09-21 15:16 UTC, merged