[week1-2] 간단한 사칙연산 계산기 구현
CodeSoom/week1-assignment-2 pull request #47
Opened 2020-09-18 12:29 UTC by shinseungyup

[구현]
1. 숫자를 누르면 누른 숫자가 출력
2. 숫자를 연속해서 누르면 숫자가 더해져서 출력

아직 어떻게 구현할지 감이 안와서 지금까지 구현한 것 먼저 PR 올립니다.
맞는 방향으로 하고 있는지 아직 잘 모르겠네요
더 고민해보고 내일까지 구현 마무리 하도록 하겠습니다

2020-09-18 18:18 UTC, Kihyun92 requested changes
리뷰가 늦었네요..🙏 
음 맞는 방향으로 잘 하고있는지 모르실땐, 가능한 작은 기능 단위로 쪼개고 하나하나 해결 해보는건 어떨까요?
예를 들면 숫자 버튼 눌렀을때 숫자 노출되게하고, 그 다음 십의 자리, 백의 자리수까지 표현이 가능하게 하고, 다음으로 더하기 기능도 추가하는 방식 처럼요. 이런식으로 점진적으로 작업을 진행해보셔도 좋을 것 같습니다~

그리고 중간 중간 의미있는 성과가 나타났을때 커밋을 남김으로써 혹시라도 길을 잃었을 경우, 다시 돌아갈 수 있게 하는 것도 좋을 것 같습니다 :)

2020-09-18 18:18 UTC, Kihyun92 commented on src/index.js
> +            <button type="button" onClick={(event) => onNumberClick(event)}>{number}</button>
이 상황에서는 event를 직접 가져오는것보다, number를 이용하는게 좋을 것 같습니다~

그리고 이렇게만 해도 event는 넘어갑니다.
```suggestion
            <button type="button" onClick={onNumberClick}>{number}</button>
```

2020-09-18 18:18 UTC, Kihyun92 commented on src/index.js
> +    }
`else if`, `else`는 사용하지 않으면서 구현하면 좋을것 같습니다~ 코드의 복잡도가 올라가고, 예측하기 어려운 코드를 만들게 합니다 ☺️

2020-09-18 18:18 UTC, Kihyun92 commented on src/index.js
> +  function onNumberClick(event) {
onClickNumber로 하는게 더 자연스러울 것 같습니다~

참고
- https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Event_handlers
- https://reactjs.org/docs/handling-events.html
- https://blog.sonim1.com/220

2020-09-19 11:17 UTC, shinseungyup commented
일단 기능 구현에 집중해서 완료하였습니다.
리뷰로 지적해주시면 다시 코드 수정하도록 하겠습니다.

2020-09-19 11:19 UTC, shinseungyup commented on src/index.js
> +    }
else if, else를 안쓰긴 했는데 제가 짠 코드처럼 if문을 계속 사용해서 구현한게 맞는건지 잘 모르겠습니다. 어떻게 할지 정확히 몰라서 일단 if문으로만 구현하였습니다.

2020-09-19 11:21 UTC, shinseungyup commented on src/index.js
> +  function onNumberClick(event) {
참고 글이 도움이 됐습니다. 앞으로 네이밍도 조금 더 신경써야겠습니다.

2020-09-19 16:13 UTC, Kihyun92 requested changes
몇몇 요인들 때문에 코드가 복잡해지고, 예외처리가 많아진 것 같습니다.
왜 이런 예외처리가 추가됐을지, 중복로직이 왜 생긴건지 그 원인을 고민해보시면 좋을 것 같습니다 😁

2020-09-19 16:13 UTC, Kihyun92 commented on src/index.js
> +  }
각 operator별로 조건문을 쓰지 않는 방법은 없을까요? 계산 로직을 object로 관리하는건 어떨까요? 그리고 함수의 리턴 타입은 일치시켜주는게 좋을 것 같습니다.

추가로 nextOper와 같이 변수명을 줄여서 쓰지 말아주세요. 본인만 이해되는 변수명은 매우 안좋습니다. 간결하고 명확하게 남들에게 설명을 굳이 하지 않아도 되는 변수명을 사용할 수 있도록 고민 해보시면 좋을 것 같습니다~

2020-09-19 16:13 UTC, Kihyun92 commented on src/index.js
> +        parseInt(prevNumber + String(number), 10), nextNumber, prevOperaion,
render함수로 넘기는 상태값들이 string 타입이라 복잡하게 형변환 과정을 여러번 거치게 된것 같아요.

이전 숫자 * 10 + 새로운 숫자로 표현하면 어떨까요?

2020-09-19 16:13 UTC, Kihyun92 commented on src/index.js
> +    }
operations에서 '='를 분리한다면 어떨까요?

2020-09-19 18:33 UTC, ahastudio commented
Lookup Table Pattern을 써보시면 코드가 좀더 단순해질 거예요.

https://medium.com/@omwri/javascript-patterns-lookup-tables-26bbaf693e24

2020-09-20 12:06 UTC, shinseungyup commented on src/index.js
> +  }
Lookup Table Pattern 이라는 것을 알게 되었고 이를 적용해서 수정했습니다.

2020-09-20 12:07 UTC, shinseungyup commented on src/index.js
> +        parseInt(prevNumber + String(number), 10), nextNumber, prevOperaion,
불필요하게 형변환 과정을 하고 있었네요. 숫자형으로 수정하였습니다.

2020-09-20 12:12 UTC, shinseungyup commented on src/index.js
> +    }
operations에서 '='를 분리한다는 것이 어떤 의미인지 이해를 못했습니다. 제 나름대로 생각해서 if문에서 operation이 '='랑 같은지 비교하는 구문은 불필요한거 같아 삭제하였습니다.

2020-09-20 12:25 UTC, shinseungyup commented
리뷰에서 지적받은 것들을 수정하려고 노력했지만 제대로 수정한건지 잘 모르겠네요.
불변성을 잘 지키고 있는건지도 고민이 되기도 합니다

2020-09-20 16:20 UTC, Kihyun92 commented on src/index.js
> +    }
결과를 계산하는 로직을 따로 함수로 만든다면 예외처리가 없어 질 것 같아서 말씀드린 부분이었습니다~
고민해보시고 좋은 해결을 찾아내신것 같네요! 좋습니다 💯

2020-09-20 16:22 UTC, Kihyun92 approved these changes
고생하셨습니다~ 처음 작성하신 코드와 최종 코드를 한번 비교하면서 어떤게 바뀌었는지, 한번 돌아보는 시간을 가지면 좋을 것 같습니다~
앞으로도 막히거나 궁금한 내용이 있다면, 함께 이야기해서 해결하면 좋을 것  같아요. :)

2020-10-05 12:53 UTC, merged