Refactor the overall code according to the change requests.
CodeSoom/week1-assignment-2 pull request #49
Opened 2020-09-18 15:32 UTC by hyejineee

## 요구사항

- [x]  ESLint를 돌린 결과 아무런 문제가 없어야 합니다.
- [x]  모든 인수 테스트를 통과시켜야 합니다.

## 구현할 기능들

- [x]  숫자를 누르면 누른 숫자가 출력되어야 합니다.
- [x]  숫자를 연속해서 누르면 숫자가 더해져서 출력되어야 합니다.
- [x]  숫자와 연산자를 입력한 후 =를 클릭하면 계산 결과가 출력되어야 합니다.
- [x]  연속해서 숫자와 연산자를 입력하면 중간에 계산 결과가 출력되어야 합니다.

## 상태&질의 
- 함수형으로 욕심부려 풀다가 중간중간 헛다리를 많이 짚은 것 같습니다.
- 이제 시작은 미약하게..!
- 하지만 이게 함수형으로 푸는 방향이 맞는 건지 의심스럽습니다.
- 강하게 휫치-휫치- 🤾🏻‍♀️부탁드립니다.

## 변경 요청사항 
@hannut91 @Kihyun92

- 기현님 피드백
   - [x] 매개변수를 노출되는 순서로 배치하는 것이 좋을 것 같다.
   - [x] 형 변환 보다 계산 식을 사용해서 숫자를 만들면 좋을 것 같다.

- 윤석님 피드백
   - [x] makeNumberUsingClickedNumber에 불필요한 정보들이 있다.
   - [x] 숫자 버튼을 생성하는 부분이 복잡하다.
   - [x] 버튼 클릭 부분이 복잡한 로직을 갖고 있기 때문에 핸들로 함수로 추출하여 작성하는 것이 좋을 것 같다.
   - [x] `result` 함수가 아니라 어떤 결과값을 나타내는 것 같다. 실제로 함수가 하는 일을 설명하는 이름을 지어주는 것이 좋을 것 같다.

## 변경 요청사항 작업 내용 
- 기현님의 피드백과 윤석님의 피드백을 반영하여 makeNumberUsingClickedNumber()메서드를 수정했습니다. \
- 숫자 버튼을 생성하는 부분이 복잡하다. 는 윤석님의 피드백을 반영하여 1-upTo까지 요소를 갖는 메서드 sequenceOfButton(upTo) 를 만들어 분리했습니다. 
- 숫자 버튼, 사칙연산 버튼의 onClick 부분의 로직을 각각 handle~Button() 메서드로 분리하였습니다. 
- result 대신 calculate로 메소드명을 수정했습니다. 위의 calculating은 연산을 하는 함수를 반환하기에 ing로 표현하여 메소드명을 지었고 
calculate는 완전히 연산을 하여 결과 값을 반환하기에 일반 동사로 메소드명을 지었습니다. 그러나 헷갈릴 수 있는 메소드명 같습니다. 
🙇🏻‍♀️ 이 부분 피드백 부탁드립니다. 🙇🏻‍♀️

2020-09-19 04:09 UTC, Kihyun92 requested changes
함수형 프로그래밍에 익숙하신것 같네요~👍 

불변성을 유지하며 구현한다는 과제의 의도와 함수형 방식은 아주 적절하다고 생각합니다. ☺️

2020-09-19 04:32 UTC, hannut91 requested changes

2020-09-19 04:32 UTC, hannut91 commented on src/index.js
> +const makeNumberUsingClickedNumber = (clickedNumber, beforeNumber) => Number(beforeNumber === 0 ? clickedNumber : `${beforeNumber}${clickedNumber}`);
선택한 숫자와 이전 숫자를 비교해서 숫자를 붙여주는 로직인 것 같아요. 하지만 이 함수에서는 `clicked`라는 컨텍스트는 불필요한 정보입니다. 단순히 숫자를 붙여주는 역할만 하고 있는 거죠.

```js
const concatNumbers = (origin, target) => {
  if (origin === 0) {
    return target;
  }
  
  return Number(`${origin}${target}`);
}
```

`before`도 불필요한 컨텍스트겠죠?

2020-09-19 04:32 UTC, hannut91 commented on src/index.js
> +const division = (num1, num2) => num1 / num2;
더하기 빼기 나누기 곱하기를 함수로 표현하신 것 같아요. 만약 우변에 있는 코드가 함수로 표현하지 않아도 충분히 의도를 드러낸다고 생각하신다면 inline function 리팩터링을 하셔도 괜찮습니다.

```js
const operatorFunctions = {
  '+': (x, y) => x + y,
  '-': (x, y) => x - y,
  '*': (x, y) => x * y,
  '/': (x, y) => x / y,
};
```

See also
  - https://github.com/hannut91/refactoring-practice/tree/master/6.2-inline-function
  - https://refactoring.com/catalog/inlineFunction.html

2020-09-19 04:32 UTC, hannut91 commented on src/index.js
> +          Array.from({ length: 9 }).map((_, i) => (
`i`를 사용할 때 계쏙 `i + 1`하는 것보다는 

```js
Array.from({ length: 9 }, (_, i) => i + 1).map((i) => {
  ...
});
```

이렇게 해주는게 좋을 것 같아요. 혹은 너무 복잡해 보인다고 생각하신다면

```js
const sequence = (value) => Array.from({ length: 9 }, (_, i) => i + 1);

sequence.map((it) => {
  ...
});
```

처럼 써도 괜찮을거에요

2020-09-19 04:32 UTC, hannut91 commented on src/index.js
> +            >
복잡한 로직이 있을 때는 여기에 바로 쓰기 보다는 핸들러 함수로 추출해서 작성하는게 더 좋을 것 같아요

2020-09-19 04:32 UTC, hannut91 commented on src/index.js
> +              }}
여기도 마찬가지로 핸들러 함수로 추출해주세요

2020-09-19 04:32 UTC, hannut91 commented on src/index.js
> +  ? operation(num2) : num1);
실제로 계산을 하는 함수인거죠? `result`라고 하니 어떤 결과값을 나타내는 것 같아요. 실제로 무슨일을 하는지 설명해주는 이름을 짓는게 좋을 것 같아요

2020-09-19 04:32 UTC, hannut91 commented on src/index.js
> +function render(num1 = 0, operate, num2) {
`num1` `num2`가 의미하는게 파악하기 어려운 것 같아요. num1 num2라면 x, y로 해도 사실 상관이 없어보여요. 좀 더 의미있는 이름을 사용하는게 좋을 것 같습니다

2020-09-19 04:32 UTC, hannut91 commented on src/index.js
> +          operate !== undefined && num2 > 0 ? num2 : num1
조건부가 길어져서 괄호로 묶어주는게 더 읽기 좋을 것 같아요

```js
(operate !== undefined && num2 > 0) ? num2 : num1
```

2020-09-19 05:01 UTC, hyejineee commented on src/index.js
> +const makeNumberUsingClickedNumber = (clickedNumber, beforeNumber) => Number(beforeNumber === 0 ? clickedNumber : `${beforeNumber}${clickedNumber}`);
오! 역시 이게 더 의도를 잘 드러내는 것 같네욤. '이전에 보여진 숫자에 누른 숫자를 추가해서 보여준다.'에서 숫자에 집착한 것 같아욯ㅎㅎㅎㅎ 수정하겠습니다!!

2020-09-19 05:08 UTC, hyejineee commented on src/index.js
> +const makeNumberUsingClickedNumber = (clickedNumber, beforeNumber) => Number(beforeNumber === 0 ? clickedNumber : `${beforeNumber}${clickedNumber}`);
오... 이 방법 생각했는데 일단 쉽게 가자 생각해서 형변환을 사용한거거든요😅😅 다시 한번 머리 굴려서 해보겠습니다!

2020-09-19 05:12 UTC, hyejineee commented on src/index.js
> +            >
오... 핸들러를 사용하면 render()함수가 정의 이잔에 사용 되어서 린트 통과 시킬려고 이렇게 한건데 생각을 더 해봐야겠네요🤔🤔

2020-09-19 17:05 UTC, Kihyun92 requested changes
점점 개선되고 있는게 느껴지네요~

매개변수가 많아지는 경우에 생각보다 복잡도가 올라갈 수 있습니다. 공통된 의미를 가지는 객체로 묶거나, 불필요한 파라미터를 제거한다면 전반적으로 많은 부분이 개선될 것 같네요.👍

2020-09-19 17:05 UTC, Kihyun92 commented on src/index.js
> +              onClick={() => (render(...handleNumberButton(num1, operate, num2, i)))}
넘겨주는 파라미터의 값이 많아서 전체적으로 복잡해지는것 같습니다. num1과 num2의 역할 구분도 되지 않구요. 쉽진 않겠지만, 불필요한 파라미터가 있지는 않은지 한번 고민해보시면 좋을 것 같습니다~

2020-09-19 18:43 UTC, ahastudio commented
계산기 로직이 `handleOperationButton` 같은 핸들러와 `onClick`에 나눠져서 있어서 한번에 이해하기 어렵습니다. 수정사항이 발생하면 관련된 부분을 동시에 고려해서 작업해야 해서 소프트웨어가 커지면 관리하기 힘들어집니다.

2020-09-20 07:46 UTC, hyejineee commented on src/index.js
> +const concatNumbers = (origin, target) => (origin === 0 ? target : (origin * 10) + target);
엌ㅋㅋㅋㅋㅋㅋㅋ바보 같았네여...ㅋㅋㅋㅋ큐ㅠ 수정하겠습니다!

2020-09-20 07:50 UTC, hyejineee commented on src/index.js
> +  calculating(calculate(num1, operate, num2))(operation),
역시...제가 리팩터링 하면서 이 부분 커밋 내용에 

' result 대신 calculate로 메소드명을 수정했습니다. 위의 calculating은 연산을 하는 함수를 반환하기에 ing로 표현하여 메소드명을 지었고
calculate는 완전히 연산을 하여 결과 값을 반환하기에 일반 동사로 메소드명을 지었습니다. 그러나 헷갈릴 수 있는 메소드명 같습니다.
🙇🏻‍♀️ 이 부분 피드백 부탁드립니다. 🙇🏻‍♀️ ' 

라고 적었거든요... calculating()메소드명에 계산 단계(?)를 반환한다. 라는 의미가 들어가면 좋을까요...??

2020-09-20 07:51 UTC, hyejineee commented on src/index.js
> +              onClick={() => (render(...handleNumberButton(num1, operate, num2, i)))}
넵!! 한 번 해보겠습니다.!

2020-09-20 14:52 UTC, Kihyun92 approved these changes
고생하셨습니다~ 회고 남겨주신것도 잘 봤습니다. 시작이 너무 좋네요~👍

처음 작성하신 코드와 최종 코드를 비교해보면서 어떻게 변했는지 비교해보시면 좋을 것 같아요~ 그리고 문제풀이 영상도 꼭 참고하셔서 차주에는 더 좋은 코드를 만드는데 도움이 됐으면 좋겠습니다~

2020-09-21 05:09 UTC, hyejineee commented
문제 풀이 영상도 있었군요ㅎㅎㅅㅎ 넵 알겠습니다!

2020-09-22 13:52 UTC, hannut91 requested changes

2020-09-22 13:52 UTC, hannut91 commented on src/index.js
> +};
x, y는 어떨까요? 이해하는데 어려움이 있을까요?

2020-09-22 13:52 UTC, hannut91 commented on src/index.js
> +const getCalculationStep = (num1) => (operation) => (num2) => operation(num1, num2);
함수를 커링한다고해서 스텝이 생기는건 아니에요. 

calculate(a, b, c)를 커링하여
calculate(a)(b)(c)를 했다고 해서 
calculate가 다른 것으로 바뀌는건 아닌 것 처럼요

2020-09-22 13:52 UTC, hannut91 commented on src/index.js
> +const sequenceOfButton = (upTo) => Array.from({ length: upTo }, (_, i) => i + 1);
해당 함수만 보면 함수 이름에 왜 Button이 들어갔는지 이해하기 어려워요. 다른 컨텍스트가 이 함수에 영향을 주고 있는 것 같은데 끊어야 합니다.

2020-09-22 13:52 UTC, hannut91 commented on src/index.js
> +      number: (!numberResetFlag ? concatNumbers(number, i) : concatNumbers(0, i)),
조건문에 부정이 들어가면 이해하기가 상당히 어려워집니다. 긍정문으로 바꿔서 표현할 수 있을까요?

혹은 다음과 같이 쓰는건 어떤가요?

```js
concatNumbers((numberResetFlag ? 0 : number), i)
```

2020-09-22 13:59 UTC, hyejineee commented on src/index.js
> +};
음 사실 x, y랑 num1,num2가 무슨 차이인지 모르겠어요... 숫자가 들어오니 number라는 걸 알려주면 좋을 것 같은데... x,y로 사용해야 하는 이유가 있나요???

2020-09-22 14:11 UTC, hyejineee commented on src/index.js
> +const getCalculationStep = (num1) => (operation) => (num2) => operation(num1, num2);
저 같은 경우 단계별로 커링해서 render()의 calculate로 넘겨주고 있거든요. 커링해서 함수를 return 받는 메소드보다 render()안에서 쓰이는 calculate가 더 실제 계산 하는 거에 가깝다고 생각해서 커링하는 메소드를 다른 메소드명으로 지었는데...ㅠㅠㅠㅠㅠ

함수형으로 작업하면 이렇게 메소드명이 중복된다고 생각되는 게 종종 있어요ㅜㅜ 이럴 때 어떻게 하면 좋을까여ㅕㅓㅠㅠㅠㅠ

2020-09-22 14:13 UTC, hyejineee commented on src/index.js
> +const sequenceOfButton = (upTo) => Array.from({ length: upTo }, (_, i) => i + 1);
button에 표시되는 인덱스들을 만드는 메소드라 이렇게 네이밍 했는데 분리해서 만들거면 컨텍스트와 완전히 분리해서 만들어야 하는군요!! 알겠습니다!!

2020-09-22 14:13 UTC, hannut91 commented on src/index.js
> +};
먼저 저는 비숫한 이름에 숫자만 바뀌기 때문에 헷갈리는 것 같아요. 철자가 유사한 변수이름을 쓰면 헷갈릴 우려가 있어요. `data`와 `date`처럼요. 1과 2가 거의 사실 의미를 많이 드러내지 않기도 하구요.

See also
  - https://ko.javascript.info/ninja-code#ref-800

2020-09-22 14:14 UTC, hyejineee commented on src/index.js
> +      number: (!numberResetFlag ? concatNumbers(number, i) : concatNumbers(0, i)),
호오.... 천재....

2020-09-22 14:18 UTC, hyejineee commented on src/index.js
> +};
오.... 하지 말라는거 다 하고 있었네....ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ큐ㅠ 좋은 자료 감사합니다!!

2020-10-05 12:52 UTC, merged